from _typeshed import Incomplete
from whoosh.analysis.acore import Composable as Composable, CompositionError as CompositionError
from whoosh.analysis.filters import LowercaseFilter as LowercaseFilter, STOP_WORDS as STOP_WORDS, StopFilter as StopFilter
from whoosh.analysis.intraword import IntraWordFilter as IntraWordFilter
from whoosh.analysis.morph import StemFilter as StemFilter
from whoosh.analysis.tokenizers import CommaSeparatedTokenizer as CommaSeparatedTokenizer, IDTokenizer as IDTokenizer, RegexTokenizer as RegexTokenizer, SpaceSeparatedTokenizer as SpaceSeparatedTokenizer, Tokenizer as Tokenizer, default_pattern as default_pattern
from whoosh.lang.porter import stem as stem

class Analyzer(Composable):
    def __eq__(self, other): ...
    def __call__(self, value, **kwargs) -> None: ...
    def clean(self) -> None: ...

class CompositeAnalyzer(Analyzer):
    items: Incomplete
    def __init__(self, *composables) -> None: ...
    def __call__(self, value, no_morph: bool = False, **kwargs): ...
    def __getitem__(self, item): ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def clean(self) -> None: ...
    def has_morph(self): ...

def IDAnalyzer(lowercase: bool = False): ...
def KeywordAnalyzer(lowercase: bool = False, commas: bool = False): ...
def RegexAnalyzer(expression: str = '\\w+(\\.?\\w+)*', gaps: bool = False): ...
def SimpleAnalyzer(expression=..., gaps: bool = False): ...
def StandardAnalyzer(expression=..., stoplist=..., minsize: int = 2, maxsize: Incomplete | None = None, gaps: bool = False): ...
def StemmingAnalyzer(expression=..., stoplist=..., minsize: int = 2, maxsize: Incomplete | None = None, gaps: bool = False, stemfn=..., ignore: Incomplete | None = None, cachesize: int = 50000): ...
def FancyAnalyzer(expression: str = '\\s+', stoplist=..., minsize: int = 2, maxsize: Incomplete | None = None, gaps: bool = True, splitwords: bool = True, splitnums: bool = True, mergewords: bool = False, mergenums: bool = False): ...
def LanguageAnalyzer(lang, expression=..., gaps: bool = False, cachesize: int = 50000): ...
