from _typeshed import Incomplete
from collections.abc import Generator
from logging import Logger
from typing import Iterable
from whoosh.analysis.acore import Composable as Composable
from whoosh.compat import next as next, xrange as xrange
from whoosh.util.text import rcompile as rcompile

STOP_WORDS: Incomplete
url_pattern: Incomplete

class Filter(Composable):
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Iterable[str]: ...

class PassFilter(Filter):
    def __call__(self, tokens: Iterable[str]) -> Iterable[str]: ...

class LoggingFilter(Filter):
    logger: Logger
    def __init__(self, logger: Logger | None = None) -> None: ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class MultiFilter(Filter):
    default_filter: Incomplete
    filters: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]): ...

class TeeFilter(Filter):
    filters: Incomplete
    def __init__(self, *filters) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class ReverseTextFilter(Filter):
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class LowercaseFilter(Filter):
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class StripFilter(Filter):
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class StopFilter(Filter):
    stops: Incomplete
    min: Incomplete
    max: Incomplete
    renumber: Incomplete
    def __init__(self, stopIterable=..., minsize: int = 2, maxsize: Incomplete | None = None, renumber: bool = True, lang: Incomplete | None = None) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class CharsetFilter(Filter):
    __inittypes__: Incomplete
    charmap: Incomplete
    def __init__(self, charmap) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class DelimitedAttributeFilter(Filter):
    delim: Incomplete
    attr: Incomplete
    default: Incomplete
    type: Incomplete
    def __init__(self, delimiter: str = '^', attribute: str = 'boost', default: float = 1.0, type=...) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...

class SubstitutionFilter(Filter):
    pattern: Incomplete
    replacement: Incomplete
    def __init__(self, pattern, replacement) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, tokens: Iterable[str]) -> Generator[str, None, None]: ...
