from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.analysis.acore import Composable as Composable, Token as Token
from whoosh.compat import text_type as text_type, u as u
from whoosh.util.text import rcompile as rcompile

default_pattern: Incomplete

class Tokenizer(Composable):
    def __eq__(self, other): ...

class IDTokenizer(Tokenizer):
    def __call__(self, value, positions: bool = False, chars: bool = False, keeporiginal: bool = False, removestops: bool = True, start_pos: int = 0, start_char: int = 0, mode: str = '', **kwargs) -> Generator[Incomplete]: ...

class RegexTokenizer(Tokenizer):
    expression: Incomplete
    gaps: Incomplete
    def __init__(self, expression=..., gaps: bool = False) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, value, positions: bool = False, chars: bool = False, keeporiginal: bool = False, removestops: bool = True, start_pos: int = 0, start_char: int = 0, tokenize: bool = True, mode: str = '', **kwargs) -> Generator[Incomplete]: ...

class CharsetTokenizer(Tokenizer):
    __inittype__: Incomplete
    charmap: Incomplete
    def __init__(self, charmap) -> None: ...
    def __eq__(self, other): ...
    def __call__(self, value, positions: bool = False, chars: bool = False, keeporiginal: bool = False, removestops: bool = True, start_pos: int = 0, start_char: int = 0, tokenize: bool = True, mode: str = '', **kwargs) -> Generator[Incomplete]: ...

def SpaceSeparatedTokenizer(): ...
def CommaSeparatedTokenizer(): ...

class PathTokenizer(Tokenizer):
    expr: Incomplete
    def __init__(self, expression: str = '[^/]+') -> None: ...
    def __call__(self, value, positions: bool = False, start_pos: int = 0, **kwargs) -> Generator[Incomplete]: ...
