repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy uscensus
        language: system
        types: [python]
        pass_filenames: false
