import time
from bisect import bisect_left as bisect_left
from whoosh.compat import xrange as xrange

IDCHARS: str
now = time.perf_counter
now = time.time

def random_name(size: int = 28): ...
def random_bytes(size: int = 28): ...
def make_binary_tree(fn, args, **kwargs): ...
def make_weighted_tree(fn, ls, **kwargs): ...
def fib(n): ...
def synchronized(func): ...
def unclosed(method): ...
