from whoosh.compat import iteritems as iteritems, xrange as xrange

class Counter(dict):
    def __missing__(self, key): ...

def unbound_cache(func): ...
def lru_cache(maxsize: int = 100): ...
def lfu_cache(maxsize: int = 100): ...
def random_cache(maxsize: int = 100): ...
def db_lru_cache(maxsize: int = 100): ...
def clockface_lru_cache(maxsize: int = 100): ...
