from _typeshed import Incomplete

def try_for(fn, timeout: float = 5.0, delay: float = 0.1): ...

class LockBase:
    fd: Incomplete
    filename: Incomplete
    locked: bool
    def __init__(self, filename) -> None: ...
    def __del__(self) -> None: ...
    def acquire(self, blocking: bool = False) -> None: ...
    def release(self) -> None: ...

class FcntlLock(LockBase):
    fd: Incomplete
    locked: bool
    def acquire(self, blocking: bool = False): ...
    def release(self) -> None: ...

class MsvcrtLock(LockBase):
    fd: Incomplete
    def acquire(self, blocking: bool = False): ...
    def release(self) -> None: ...

FileLock = FcntlLock
