import pickle
from _typeshed import Incomplete

class RenamingUnpickler(pickle.Unpickler):
    def __init__(self, f, objmap, shortcuts: Incomplete | None = None) -> None: ...
    def find_class(self, modulename, objname): ...

def find_object(name, blacklist: Incomplete | None = None, whitelist: Incomplete | None = None): ...
