from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import b as b, long_type as long_type
from whoosh.system import pack_byte as pack_byte, pack_double as pack_double, pack_float as pack_float, pack_int as pack_int, pack_long as pack_long, pack_uint as pack_uint, pack_ulong as pack_ulong, pack_ushort as pack_ushort, unpack_byte as unpack_byte, unpack_double as unpack_double, unpack_float as unpack_float, unpack_int as unpack_int, unpack_long as unpack_long, unpack_uint as unpack_uint, unpack_ulong as unpack_ulong, unpack_ushort as unpack_ushort

NaN: Incomplete
typecode_max: Incomplete
typecode_min: Incomplete
typecode_pack: Incomplete
typecode_unpack: Incomplete

def bits_required(maxnum): ...
def typecode_required(maxnum): ...
def max_value(bitcount): ...
def bytes_for_bits(bitcount): ...
def to_sortable(numtype, intsize, signed, x): ...
def from_sortable(numtype, intsize, signed, x): ...
def float_to_sortable_long(x, signed): ...
def sortable_long_to_float(x, signed): ...
def split_ranges(intsize, step, start, end) -> Generator[Incomplete, None, Incomplete]: ...
def tiered_ranges(numtype, intsize, signed, start, end, shift_step, startexcl, endexcl): ...
def float_to_byte(value, mantissabits: int = 5, zeroexp: int = 2): ...
def byte_to_float(b, mantissabits: int = 5, zeroexp: int = 2): ...
def length_to_byte(length): ...

byte_to_length: Incomplete
