from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import xrange as xrange
from whoosh.system import emptybytes as emptybytes, pack_byte as pack_byte, pack_uint_le as pack_uint_le, pack_ushort_le as pack_ushort_le, unpack_byte as unpack_byte, unpack_uint_le as unpack_uint_le, unpack_ushort_le as unpack_ushort_le

def delta_encode(nums) -> Generator[Incomplete]: ...
def delta_decode(nums) -> Generator[Incomplete]: ...

class GrowableArray:
    array: Incomplete
    def __init__(self, inittype: str = 'B', allow_longs: bool = True) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def append(self, n) -> None: ...
    def extend(self, ns) -> None: ...
    @property
    def typecode(self): ...
    def to_file(self, dbfile) -> None: ...

class NumberEncoding:
    maxint: Incomplete
    def write_nums(self, f, numbers) -> None: ...
    def read_nums(self, f, n) -> Generator[int, None, None]: ...
    def write_deltas(self, f, numbers): ...
    def read_deltas(self, f, n): ...
    def get(self, f, pos, i): ...

class FixedEncoding(NumberEncoding):
    size: Incomplete
    def write_nums(self, f, numbers) -> None: ...
    def read_nums(self, f, n) -> Generator[int, None, None]: ...
    def get(self, f, pos, i): ...

class ByteEncoding(FixedEncoding):
    size: int
    maxint: int

class UShortEncoding(FixedEncoding):
    size: int
    maxint: Incomplete

class UIntEncoding(FixedEncoding):
    size: int
    maxint: Incomplete

class Varints(NumberEncoding):
    maxint: Incomplete
    def write_nums(self, f, numbers) -> None: ...
    def read_nums(self, f, n) -> Generator[int, None, None]: ...

class Simple16(NumberEncoding):
    maxint: Incomplete
    def write_nums(self, f, numbers) -> None: ...
    def read_nums(self, f, n) -> Generator[int, None, None]: ...
    def get(self, f, pos, i): ...

class GInts(NumberEncoding):
    maxint: Incomplete
    def key_to_sizes(self, key): ...
    def write_nums(self, f, numbers) -> None: ...
    def read_nums(self, f, n) -> Generator[int, None, None]: ...
