from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import byte as byte, string_type as string_type, u as u

utf8encode: Incomplete
utf8decode: Incomplete

def first_diff(a, b): ...
def prefix_encode(a, b): ...
def prefix_encode_all(ls) -> Generator[Incomplete]: ...
def prefix_decode_all(ls) -> Generator[Incomplete]: ...
def natural_key(s): ...
def rcompile(pattern, flags: int = 0, verbose: bool = False): ...
