from _typeshed import Incomplete
from whoosh.compat import iteritems as iteritems

class TimeError(Exception): ...

def relative_days(current_wday, wday, dir): ...
def timedelta_to_usecs(td): ...
def datetime_to_long(dt): ...
def long_to_datetime(x): ...

class adatetime:
    units: Incomplete
    microsecond: Incomplete
    def __init__(self, year: Incomplete | None = None, month: Incomplete | None = None, day: Incomplete | None = None, hour: Incomplete | None = None, minute: Incomplete | None = None, second: Incomplete | None = None, microsecond: Incomplete | None = None) -> None: ...
    def __eq__(self, other): ...
    def tuple(self): ...
    def date(self): ...
    def copy(self): ...
    def replace(self, **kwargs): ...
    def floor(self): ...
    def ceil(self): ...
    def disambiguated(self, basedate): ...

class timespan:
    start: Incomplete
    end: Incomplete
    def __init__(self, start, end) -> None: ...
    def __eq__(self, other): ...
    def disambiguated(self, basedate, debug: int = 0): ...

def floor(at): ...
def ceil(at): ...
def fill_in(at, basedate, units=...): ...
def has_no_date(at): ...
def has_no_time(at): ...
def is_ambiguous(at): ...
def is_void(at): ...
def fix(at): ...
