from whoosh.compat import array_tobytes as array_tobytes, xrange as xrange

def varint(i): ...
def varint_to_int(vi): ...
def signed_varint(i): ...
def decode_signed_varint(i): ...
def read_varint(readfn): ...
