from _typeshed import Incomplete
from whoosh.util.text import rcompile as rcompile

class BaseVersion:
    @classmethod
    def parse(cls, text): ...
    def tuple(self): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __le__(self, other): ...
    def __ne__(self, other): ...

class SimpleVersion(BaseVersion):
    major: Incomplete
    minor: Incomplete
    release: Incomplete
    ex: Incomplete
    exnum: Incomplete
    def __init__(self, major: int = 1, minor: int = 0, release: int = 0, ex: str = 'z', exnum: int = 0) -> None: ...
    def to_int(self): ...
    @classmethod
    def from_int(cls, n): ...
