from _typeshed import Incomplete
from whoosh.compat import string_type as string_type

class QueryParserError(Exception):
    cause: Incomplete
    def __init__(self, cause, msg: Incomplete | None = None) -> None: ...

def get_single_text(field, text, **kwargs): ...
def attach(q, stxnode): ...
def print_debug(level, msg, out=...) -> None: ...
