from _typeshed import Incomplete
from whoosh import query as query
from whoosh.compat import text_type as text_type
from whoosh.qparser import syntax as syntax
from whoosh.qparser.common import QueryParserError as QueryParserError, print_debug as print_debug

class QueryParser:
    fieldname: Incomplete
    schema: Incomplete
    termclass: Incomplete
    phraseclass: Incomplete
    group: Incomplete
    plugins: Incomplete
    def __init__(self, fieldname, schema, plugins: Incomplete | None = None, termclass=..., phraseclass=..., group=...) -> None: ...
    def default_set(self): ...
    def add_plugins(self, pins) -> None: ...
    def add_plugin(self, pin) -> None: ...
    def remove_plugin(self, pi) -> None: ...
    def remove_plugin_class(self, cls) -> None: ...
    def replace_plugin(self, plugin) -> None: ...
    def multitoken_query(self, spec, texts, fieldname, termclass, boost): ...
    def term_query(self, fieldname, text, termclass, boost: float = 1.0, tokenize: bool = True, removestops: bool = True): ...
    def taggers(self): ...
    def filters(self): ...
    def tag(self, text, pos: int = 0, debug: bool = False): ...
    def filterize(self, nodes, debug: bool = False): ...
    def process(self, text, pos: int = 0, debug: bool = False): ...
    def parse(self, text, normalize: bool = True, debug: bool = False): ...
    def parse_(self, text, normalize: bool = True) -> None: ...

def MultifieldParser(fieldnames, schema, fieldboosts: Incomplete | None = None, **kwargs): ...
def SimpleParser(fieldname, schema, **kwargs): ...
def DisMaxParser(fieldboosts, schema, tiebreak: float = 0.0, **kwargs): ...
