from _typeshed import Incomplete
from whoosh import query as query
from whoosh.qparser.common import QueryParserError as QueryParserError, attach as attach, get_single_text as get_single_text

class SyntaxNode:
    has_fieldname: bool
    has_text: bool
    has_boost: bool
    def r(self): ...
    def apply(self, fn): ...
    def accept(self, fn): ...
    def query(self, parser) -> None: ...
    def is_ws(self): ...
    def is_text(self): ...
    fieldname: Incomplete
    def set_fieldname(self, name, override: bool = False): ...
    boost: Incomplete
    def set_boost(self, boost): ...
    startchar: Incomplete
    endchar: Incomplete
    def set_range(self, startchar, endchar): ...
    def parent(self): ...
    def next_sibling(self): ...
    def prev_sibling(self): ...
    def bake(self, parent) -> None: ...

class MarkerNode(SyntaxNode):
    def r(self): ...

class Whitespace(MarkerNode):
    def r(self): ...
    def is_ws(self): ...

class FieldnameNode(SyntaxNode):
    has_fieldname: bool
    fieldname: Incomplete
    original: Incomplete
    def __init__(self, fieldname, original) -> None: ...

class GroupNode(SyntaxNode):
    has_boost: bool
    merging: bool
    qclass: Incomplete
    nodes: Incomplete
    boost: Incomplete
    kwargs: Incomplete
    def __init__(self, nodes: Incomplete | None = None, boost: float = 1.0, **kwargs) -> None: ...
    def r(self): ...
    @property
    def startchar(self): ...
    @property
    def endchar(self): ...
    def apply(self, fn): ...
    def query(self, parser): ...
    def empty_copy(self): ...
    def set_fieldname(self, name, override: bool = False) -> None: ...
    def set_range(self, startchar, endchar): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __getitem__(self, n): ...
    def __setitem__(self, n, v) -> None: ...
    def __delitem__(self, n) -> None: ...
    def insert(self, n, v) -> None: ...
    def append(self, v) -> None: ...
    def extend(self, vs) -> None: ...
    def pop(self, *args, **kwargs): ...
    def reverse(self) -> None: ...
    def index(self, v): ...
    def bake(self, parent) -> None: ...
    def node_before(self, n): ...
    def node_after(self, n): ...

class BinaryGroup(GroupNode):
    merging: bool
    has_boost: bool
    def query(self, parser): ...

class Wrapper(GroupNode):
    merging: bool
    def query(self, parser): ...

class ErrorNode(SyntaxNode):
    message: Incomplete
    node: Incomplete
    def __init__(self, message, node: Incomplete | None = None) -> None: ...
    def r(self): ...
    @property
    def startchar(self): ...
    @property
    def endchar(self): ...
    def query(self, parser): ...

class AndGroup(GroupNode):
    qclass: Incomplete

class OrGroup(GroupNode):
    qclass: Incomplete
    @classmethod
    def factory(cls, scale: float = 1.0): ...

class DisMaxGroup(GroupNode):
    qclass: Incomplete

class OrderedGroup(GroupNode):
    qclass: Incomplete

class AndNotGroup(BinaryGroup):
    qclass: Incomplete

class AndMaybeGroup(BinaryGroup):
    qclass: Incomplete

class RequireGroup(BinaryGroup):
    qclass: Incomplete

class NotGroup(Wrapper):
    qclass: Incomplete

class RangeNode(SyntaxNode):
    has_fieldname: bool
    start: Incomplete
    end: Incomplete
    startexcl: Incomplete
    endexcl: Incomplete
    boost: float
    fieldname: Incomplete
    kwargs: Incomplete
    def __init__(self, start, end, startexcl, endexcl) -> None: ...
    def r(self): ...
    def query(self, parser): ...

class TextNode(SyntaxNode):
    has_fieldname: bool
    has_text: bool
    has_boost: bool
    qclass: Incomplete
    tokenize: bool
    removestops: bool
    fieldname: Incomplete
    text: Incomplete
    boost: float
    def __init__(self, text) -> None: ...
    def r(self): ...
    def is_text(self): ...
    def query(self, parser): ...

class WordNode(TextNode):
    tokenize: bool
    removestops: bool
    def r(self): ...

class Operator(SyntaxNode):
    text: Incomplete
    grouptype: Incomplete
    leftassoc: Incomplete
    def __init__(self, text, grouptype, leftassoc: bool = True) -> None: ...
    def r(self): ...
    def replace_self(self, parser, group, position) -> None: ...

class PrefixOperator(Operator):
    def replace_self(self, parser, group, position): ...

class PostfixOperator(Operator):
    def replace_self(self, parser, group, position): ...

class InfixOperator(Operator):
    def replace_self(self, parser, group, position): ...

def to_word(n): ...
