from _typeshed import Incomplete
from whoosh.util.text import rcompile as rcompile

class Tagger:
    def match(self, parser, text, pos) -> None: ...

class RegexTagger(Tagger):
    expr: Incomplete
    def __init__(self, expr) -> None: ...
    def match(self, parser, text, pos): ...
    def create(self, parser, match) -> None: ...

class FnTagger(RegexTagger):
    fn: Incomplete
    memo: Incomplete
    def __init__(self, expr, fn, memo: str = '') -> None: ...
    def create(self, parser, match): ...
