import abc
from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import columns as columns
from whoosh.automata import lev as lev
from whoosh.compat import abstractmethod as abstractmethod, izip as izip, unichr as unichr, xrange as xrange
from whoosh.filedb.compound import CompoundStorage as CompoundStorage
from whoosh.system import emptybytes as emptybytes
from whoosh.util import random_name as random_name

class OutOfOrderError(Exception): ...

class Codec(metaclass=abc.ABCMeta):
    length_stats: bool
    @abstractmethod
    def per_document_writer(self, storage, segment): ...
    @abstractmethod
    def field_writer(self, storage, segment): ...
    @abstractmethod
    def postings_writer(self, dbfile, byteids: bool = False): ...
    @abstractmethod
    def postings_reader(self, dbfile, terminfo, format_, term: Incomplete | None = None, scorer: Incomplete | None = None): ...
    def automata(self, storage, segment): ...
    @abstractmethod
    def terms_reader(self, storage, segment): ...
    @abstractmethod
    def per_document_reader(self, storage, segment): ...
    @abstractmethod
    def new_segment(self, storage, indexname): ...

class WrappingCodec(Codec):
    def __init__(self, child) -> None: ...
    def per_document_writer(self, storage, segment): ...
    def field_writer(self, storage, segment): ...
    def postings_writer(self, dbfile, byteids: bool = False): ...
    def postings_reader(self, dbfile, terminfo, format_, term: Incomplete | None = None, scorer: Incomplete | None = None): ...
    def automata(self, storage, segment): ...
    def terms_reader(self, storage, segment): ...
    def per_document_reader(self, storage, segment): ...
    def new_segment(self, storage, indexname): ...

class PerDocumentWriter(metaclass=abc.ABCMeta):
    @abstractmethod
    def start_doc(self, docnum): ...
    @abstractmethod
    def add_field(self, fieldname, fieldobj, value, length): ...
    @abstractmethod
    def add_column_value(self, fieldname, columnobj, value): ...
    @abstractmethod
    def add_vector_items(self, fieldname, fieldobj, items): ...
    def add_vector_matcher(self, fieldname, fieldobj, vmatcher) -> None: ...
    def finish_doc(self) -> None: ...
    def close(self) -> None: ...

class FieldWriter(metaclass=abc.ABCMeta):
    def add_postings(self, schema, lengths, items): ...
    @abstractmethod
    def start_field(self, fieldname, fieldobj): ...
    @abstractmethod
    def start_term(self, text): ...
    @abstractmethod
    def add(self, docnum, weight, vbytes, length): ...
    def add_spell_word(self, fieldname, text) -> None: ...
    @abstractmethod
    def finish_term(self): ...
    def finish_field(self) -> None: ...
    def close(self) -> None: ...

class PostingsWriter(metaclass=abc.ABCMeta):
    @abstractmethod
    def start_postings(self, format_, terminfo): ...
    @abstractmethod
    def add_posting(self, id_, weight, vbytes, length: Incomplete | None = None): ...
    def finish_postings(self) -> None: ...
    @abstractmethod
    def written(self): ...

class FieldCursor:
    def first(self) -> None: ...
    def find(self, string) -> None: ...
    def next(self) -> None: ...
    def term(self) -> None: ...

class TermsReader(metaclass=abc.ABCMeta):
    @abstractmethod
    def __contains__(self, term): ...
    @abstractmethod
    def cursor(self, fieldname, fieldobj): ...
    @abstractmethod
    def terms(self): ...
    @abstractmethod
    def terms_from(self, fieldname, prefix): ...
    @abstractmethod
    def items(self): ...
    @abstractmethod
    def items_from(self, fieldname, prefix): ...
    @abstractmethod
    def term_info(self, fieldname, text): ...
    @abstractmethod
    def frequency(self, fieldname, text): ...
    @abstractmethod
    def doc_frequency(self, fieldname, text): ...
    @abstractmethod
    def matcher(self, fieldname, text, format_, scorer: Incomplete | None = None): ...
    @abstractmethod
    def indexed_field_names(self): ...
    def close(self) -> None: ...

class Automata:
    @staticmethod
    def levenshtein_dfa(uterm, maxdist, prefix: int = 0): ...
    @staticmethod
    def find_matches(dfa, cur) -> Generator[Incomplete]: ...
    def terms_within(self, fieldcur, uterm, maxdist, prefix: int = 0): ...

class PerDocumentReader(metaclass=abc.ABCMeta):
    def close(self) -> None: ...
    @abstractmethod
    def doc_count(self): ...
    @abstractmethod
    def doc_count_all(self): ...
    @abstractmethod
    def has_deletions(self): ...
    @abstractmethod
    def is_deleted(self, docnum): ...
    @abstractmethod
    def deleted_docs(self): ...
    def all_doc_ids(self): ...
    def iter_docs(self) -> Generator[Incomplete]: ...
    def supports_columns(self): ...
    def has_column(self, fieldname): ...
    def list_columns(self) -> None: ...
    def column_reader(self, fieldname, column) -> None: ...
    def field_docs(self, fieldname) -> None: ...
    @abstractmethod
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    @abstractmethod
    def field_length(self, fieldname): ...
    @abstractmethod
    def min_field_length(self, fieldname): ...
    @abstractmethod
    def max_field_length(self, fieldname): ...
    def has_vector(self, docnum, fieldname): ...
    def vector(self, docnum, fieldname, format_) -> None: ...
    @abstractmethod
    def stored_fields(self, docnum): ...
    def all_stored_fields(self) -> Generator[Incomplete]: ...

class Segment(metaclass=abc.ABCMeta):
    COMPOUND_EXT: str
    indexname: Incomplete
    segid: Incomplete
    compound: bool
    def __init__(self, indexname) -> None: ...
    def codec(self) -> None: ...
    def index_name(self): ...
    def segment_id(self): ...
    def is_compound(self): ...
    def make_filename(self, ext): ...
    def list_files(self, storage): ...
    def create_file(self, storage, ext, **kwargs): ...
    def open_file(self, storage, ext, **kwargs): ...
    def create_compound_file(self, storage) -> None: ...
    def open_compound_file(self, storage): ...
    @abstractmethod
    def doc_count_all(self): ...
    def doc_count(self): ...
    def set_doc_count(self, doccount) -> None: ...
    def has_deletions(self): ...
    @abstractmethod
    def deleted_count(self): ...
    @abstractmethod
    def deleted_docs(self): ...
    @abstractmethod
    def delete_document(self, docnum, delete: bool = True): ...
    @abstractmethod
    def is_deleted(self, docnum): ...
    def should_assemble(self): ...

class WrappingSegment(Segment):
    def __init__(self, child) -> None: ...
    def codec(self): ...
    def index_name(self): ...
    def segment_id(self): ...
    def is_compound(self): ...
    def should_assemble(self): ...
    def make_filename(self, ext): ...
    def list_files(self, storage): ...
    def create_file(self, storage, ext, **kwargs): ...
    def open_file(self, storage, ext, **kwargs): ...
    def create_compound_file(self, storage): ...
    def open_compound_file(self, storage): ...
    def delete_document(self, docnum, delete: bool = True): ...
    def has_deletions(self): ...
    def deleted_count(self): ...
    def deleted_docs(self): ...
    def is_deleted(self, docnum): ...
    def set_doc_count(self, doccount) -> None: ...
    def doc_count(self): ...
    def doc_count_all(self): ...

class MultiPerDocumentReader(PerDocumentReader, metaclass=abc.ABCMeta):
    is_closed: bool
    def __init__(self, readers, offset: int = 0) -> None: ...
    def close(self) -> None: ...
    def doc_count_all(self): ...
    def doc_count(self): ...
    def has_deletions(self): ...
    def is_deleted(self, docnum): ...
    def deleted_docs(self) -> Generator[Incomplete]: ...
    def all_doc_ids(self) -> Generator[Incomplete]: ...
    def has_column(self, fieldname): ...
    def column_reader(self, fieldname, column): ...
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    def field_length(self, fieldname): ...
    def min_field_length(self): ...
    def max_field_length(self): ...

class PerDocWriterWithColumns(PerDocumentWriter, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    def add_column_value(self, fieldname, column, value) -> None: ...

class EmptyCursor(FieldCursor):
    def first(self) -> None: ...
    def find(self, term) -> None: ...
    def next(self) -> None: ...
    def text(self) -> None: ...
    def term_info(self) -> None: ...
    def is_valid(self): ...
