import abc
from _typeshed import Incomplete
from collections.abc import Generator
from threading import RLock as RLock
from whoosh.codec import base as base
from whoosh.compat import xrange as xrange
from whoosh.matching import ListMatcher as ListMatcher
from whoosh.reading import SegmentReader as SegmentReader, TermInfo as TermInfo, TermNotFound as TermNotFound
from whoosh.writing import SegmentWriter as SegmentWriter

class MemWriter(SegmentWriter):
    def commit(self) -> None: ...

class MemoryCodec(base.Codec, metaclass=abc.ABCMeta):
    storage: Incomplete
    segment: Incomplete
    def __init__(self) -> None: ...
    def writer(self, schema): ...
    def reader(self, schema): ...
    def per_document_writer(self, storage, segment): ...
    def field_writer(self, storage, segment): ...
    def per_document_reader(self, storage, segment): ...
    def terms_reader(self, storage, segment): ...
    def new_segment(self, storage, indexname): ...

class MemPerDocWriter(base.PerDocWriterWithColumns):
    is_closed: bool
    def __init__(self, storage, segment) -> None: ...
    def start_doc(self, docnum) -> None: ...
    def add_field(self, fieldname, fieldobj, value, length) -> None: ...
    def add_vector_items(self, fieldname, fieldobj, items) -> None: ...
    def finish_doc(self) -> None: ...
    def close(self) -> None: ...

class MemPerDocReader(base.PerDocumentReader):
    def __init__(self, storage, segment) -> None: ...
    def doc_count(self): ...
    def doc_count_all(self): ...
    def has_deletions(self): ...
    def is_deleted(self, docnum): ...
    def deleted_docs(self): ...
    def supports_columns(self): ...
    def has_column(self, fieldname): ...
    def column_reader(self, fieldname, column): ...
    def doc_field_length(self, docnum, fieldname, default: int = 0): ...
    def field_length(self, fieldname): ...
    def min_field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def has_vector(self, docnum, fieldname): ...
    def vector(self, docnum, fieldname, format_): ...
    def stored_fields(self, docnum): ...
    def close(self) -> None: ...

class MemFieldWriter(base.FieldWriter):
    is_closed: bool
    def __init__(self, storage, segment) -> None: ...
    def start_field(self, fieldname, fieldobj) -> None: ...
    def start_term(self, btext) -> None: ...
    def add(self, docnum, weight, vbytes, length) -> None: ...
    def finish_term(self) -> None: ...
    def finish_field(self) -> None: ...
    def close(self) -> None: ...

class MemTermsReader(base.TermsReader, metaclass=abc.ABCMeta):
    def __init__(self, storage, segment) -> None: ...
    def __contains__(self, term) -> bool: ...
    def terms(self) -> Generator[Incomplete]: ...
    def terms_from(self, fieldname, prefix) -> Generator[Incomplete]: ...
    def term_info(self, fieldname, text): ...
    def matcher(self, fieldname, btext, format_, scorer: Incomplete | None = None): ...
    def indexed_field_names(self): ...
    def close(self) -> None: ...

class MemSegment(base.Segment, metaclass=abc.ABCMeta):
    def __init__(self, codec, indexname) -> None: ...
    def codec(self): ...
    def set_doc_count(self, doccount) -> None: ...
    def doc_count(self): ...
    def doc_count_all(self): ...
    def delete_document(self, docnum, delete: bool = True) -> None: ...
    def has_deletions(self): ...
    def is_deleted(self, docnum): ...
    def deleted_docs(self) -> Generator[Incomplete]: ...
    def should_assemble(self): ...
