from _typeshed import Incomplete
from whoosh import matching as matching
from whoosh.compat import text_type as text_type, u as u, xrange as xrange
from whoosh.query import qcore as qcore
from whoosh.util import make_binary_tree as make_binary_tree, make_weighted_tree as make_weighted_tree

class CompoundQuery(qcore.Query):
    subqueries: Incomplete
    boost: Incomplete
    def __init__(self, subqueries, boost: float = 1.0) -> None: ...
    def __unicode__(self): ...
    def __eq__(self, other): ...
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __hash__(self): ...
    def is_leaf(self): ...
    def children(self): ...
    def apply(self, fn): ...
    def field(self): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def normalize(self): ...
    def simplify(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class And(CompoundQuery):
    JOINT: str
    intersect_merge: bool
    def requires(self): ...
    def estimate_size(self, ixreader): ...

class Or(CompoundQuery):
    JOINT: str
    intersect_merge: bool
    TOO_MANY_CLAUSES: int
    AUTO_MATCHER: int
    DEFAULT_MATCHER: int
    SPLIT_MATCHER: int
    ARRAY_MATCHER: int
    matcher_type = AUTO_MATCHER
    minmatch: Incomplete
    scale: Incomplete
    def __init__(self, subqueries, boost: float = 1.0, minmatch: int = 0, scale: Incomplete | None = None) -> None: ...
    def __unicode__(self): ...
    def normalize(self): ...
    def requires(self): ...

class DefaultOr(Or):
    JOINT: str

class SplitOr(Or):
    JOINT: str
    SPLIT_DOC_LIMIT: int
    def matcher(self, searcher, context: Incomplete | None = None): ...

class PreloadedOr(Or):
    JOINT: str

class DisjunctionMax(CompoundQuery):
    tiebreak: Incomplete
    def __init__(self, subqueries, boost: float = 1.0, tiebreak: float = 0.0) -> None: ...
    def __unicode__(self): ...
    def normalize(self): ...
    def requires(self): ...

class BinaryQuery(CompoundQuery):
    boost: float
    a: Incomplete
    b: Incomplete
    subqueries: Incomplete
    def __init__(self, a, b) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def needs_spans(self): ...
    def apply(self, fn): ...
    def field(self): ...
    def with_boost(self, boost): ...
    def normalize(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class AndNot(BinaryQuery):
    JOINT: str
    def with_boost(self, boost): ...
    def normalize(self): ...
    def requires(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class Otherwise(BinaryQuery):
    JOINT: str
    def matcher(self, searcher, context: Incomplete | None = None): ...

class Require(BinaryQuery):
    JOINT: str
    matcherclass = matching.RequireMatcher
    def requires(self): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def with_boost(self, boost): ...
    def normalize(self): ...
    def docs(self, searcher): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class AndMaybe(BinaryQuery):
    JOINT: str
    matcherclass = matching.AndMaybeMatcher
    def normalize(self): ...
    def requires(self): ...
    def estimate_min_size(self, ixreader): ...
    def docs(self, searcher): ...

def BooleanQuery(required, should, prohibited): ...
