import abc
from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import matching as matching
from whoosh.compat import text_type as text_type, u as u, xrange as xrange
from whoosh.query import qcore as qcore
from whoosh.query.wrappers import WrappingQuery as WrappingQuery

class NestedParent(WrappingQuery):
    parents: Incomplete
    child: Incomplete
    per_parent_limit: Incomplete
    score_fn: Incomplete
    def __init__(self, parents, subq, per_parent_limit: Incomplete | None = None, score_fn=...) -> None: ...
    def normalize(self): ...
    def requires(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    def deletion_docs(self, searcher) -> Generator[Incomplete]: ...
    class NestedParentMatcher(matching.Matcher, metaclass=abc.ABCMeta):
        comb: Incomplete
        child: Incomplete
        per_parent_limit: Incomplete
        maxdoc: Incomplete
        score_fn: Incomplete
        def __init__(self, comb, child, per_parent_limit, maxdoc, score_fn) -> None: ...
        def is_active(self): ...
        def supports_block_quality(self): ...
        def id(self): ...
        def score(self): ...
        def reset(self) -> None: ...
        def next(self) -> None: ...
        def skip_to(self, id) -> None: ...
        def value(self) -> None: ...
        def spans(self): ...

class NestedChildren(WrappingQuery):
    parents: Incomplete
    child: Incomplete
    boost: Incomplete
    def __init__(self, parents, subq, boost: float = 1.0) -> None: ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    class NestedChildMatcher(matching.WrappingMatcher):
        parent_comb: Incomplete
        child: Incomplete
        limit: Incomplete
        is_deleted: Incomplete
        boost: Incomplete
        def __init__(self, parent_comb, wanted_parent_matcher, limit, is_deleted, boost: float = 1.0) -> None: ...
        def reset(self) -> None: ...
        def is_active(self): ...
        def replace(self, minquality: int = 0): ...
        def id(self): ...
        def all_ids(self) -> Generator[Incomplete]: ...
        def next(self) -> None: ...
        def skip_to(self, docid) -> None: ...
        def value(self) -> None: ...
        def score(self): ...
        def spans(self): ...
