from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import matching as matching
from whoosh.analysis import Token as Token
from whoosh.compat import u as u
from whoosh.query import compound as compound, qcore as qcore, terms as terms

class Sequence(compound.CompoundQuery):
    JOINT: str
    intersect_merge: bool
    slop: Incomplete
    ordered: Incomplete
    def __init__(self, subqueries, slop: int = 1, ordered: bool = True, boost: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def normalize(self): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...

class Ordered(Sequence):
    JOINT: str

class Phrase(qcore.Query):
    fieldname: Incomplete
    words: Incomplete
    slop: Incomplete
    boost: Incomplete
    char_ranges: Incomplete
    def __init__(self, fieldname, words, slop: int = 1, boost: float = 1.0, char_ranges: Incomplete | None = None) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def has_terms(self): ...
    def terms(self, phrases: bool = False) -> Generator[Incomplete]: ...
    def tokens(self, boost: float = 1.0) -> Generator[Incomplete]: ...  # type: ignore[override]
    def normalize(self): ...
    def replace(self, fieldname, oldtext, newtext): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
