from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import matching as matching
from whoosh.compat import methodcaller as methodcaller, u as u
from whoosh.reading import TermNotFound as TermNotFound

class QueryError(Exception): ...

def error_query(msg, q: Incomplete | None = None): ...
def token_lists(q, phrases: bool = True): ...

class Lowest:
    def __cmp__(self, other): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...

class Highest:
    def __cmp__(self, other): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...

class Query:
    startchar: Incomplete
    endchar: Incomplete
    error: Incomplete
    def __unicode__(self) -> None: ...
    def __getitem__(self, item) -> None: ...
    def __or__(self, query): ...
    def __and__(self, query): ...
    def __sub__(self, query): ...
    def __hash__(self): ...
    def __ne__(self, other): ...
    def is_leaf(self): ...
    def children(self): ...
    def is_range(self): ...
    def has_terms(self): ...
    def needs_spans(self): ...
    def apply(self, fn): ...
    def accept(self, fn): ...
    def replace(self, fieldname, oldtext, newtext): ...
    def copy(self): ...
    def all_terms(self, phrases: bool = True): ...
    def terms(self, phrases: bool = False): ...
    def expanded_terms(self, ixreader, phrases: bool = True): ...
    def existing_terms(self, ixreader, phrases: bool = True, expand: bool = False, fieldname: Incomplete | None = None): ...
    def leaves(self) -> Generator[Incomplete]: ...
    def iter_all_terms(self, phrases: bool = True) -> Generator[Incomplete]: ...
    def all_tokens(self, boost: float = 1.0) -> Generator[Incomplete]: ...
    def tokens(self, boost: float = 1.0, exreader: Incomplete | None = None): ...
    def requires(self): ...
    def field(self): ...
    def with_boost(self, boost): ...
    def estimate_size(self, ixreader) -> None: ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None) -> None: ...
    def docs(self, searcher): ...
    def deletion_docs(self, searcher): ...
    def normalize(self): ...
    def simplify(self, ixreader): ...

class _NullQuery(Query):
    boost: float
    error: Incomplete
    def __init__(self) -> None: ...
    def __unicode__(self): ...
    def __call__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...
    def field(self) -> None: ...
    def estimate_size(self, ixreader): ...
    def normalize(self): ...
    def simplify(self, ixreader): ...
    def docs(self, searcher): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

NullQuery: Incomplete

class Every(Query):
    fieldname: Incomplete
    boost: Incomplete
    def __init__(self, fieldname: Incomplete | None = None, boost: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def estimate_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
