from _typeshed import Incomplete
from whoosh.compat import b as b, u as u
from whoosh.query import compound as compound, qcore as qcore, terms as terms, wrappers as wrappers
from whoosh.util.times import datetime_to_long as datetime_to_long

class RangeMixin:
    def __unicode__(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def is_range(self): ...
    def overlaps(self, other): ...
    def merge(self, other, intersect: bool = True): ...

class TermRange(RangeMixin, terms.MultiTerm):
    fieldname: Incomplete
    start: Incomplete
    end: Incomplete
    startexcl: Incomplete
    endexcl: Incomplete
    boost: Incomplete
    constantscore: Incomplete
    def __init__(self, fieldname, start, end, startexcl: bool = False, endexcl: bool = False, boost: float = 1.0, constantscore: bool = True) -> None: ...
    def normalize(self): ...

class NumericRange(RangeMixin, qcore.Query):
    fieldname: Incomplete
    start: Incomplete
    end: Incomplete
    startexcl: Incomplete
    endexcl: Incomplete
    boost: Incomplete
    constantscore: Incomplete
    def __init__(self, fieldname, start, end, startexcl: bool = False, endexcl: bool = False, boost: float = 1.0, constantscore: bool = True) -> None: ...
    def simplify(self, ixreader): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def docs(self, searcher): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class DateRange(NumericRange):
    startdate: Incomplete
    enddate: Incomplete
    def __init__(self, fieldname, start, end, startexcl: bool = False, endexcl: bool = False, boost: float = 1.0, constantscore: bool = True) -> None: ...
