from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.matching import binary as binary, mcore as mcore, wrappers as wrappers
from whoosh.query import And as And, AndMaybe as AndMaybe, Or as Or, Query as Query, Term as Term
from whoosh.util import make_binary_tree as make_binary_tree

__all__ = [
    "Span",
    "bisect_spans",
    "SpanWrappingMatcher",
    "SpanBiMatcher",
    "SpanQuery",
    "WrappingSpan",
    "SpanFirst",
    "SpanNear",
    "SpanNear2",
    "SpanOr",
    "SpanBiQuery",
    "SpanNot",
    "SpanContains",
    "SpanBefore",
    "SpanCondition",
]


class Span:
    start: Incomplete
    end: Incomplete
    startchar: Incomplete
    endchar: Incomplete
    boost: Incomplete
    def __init__(self, start, end: Incomplete | None = None, startchar: Incomplete | None = None, endchar: Incomplete | None = None, boost: float = 1.0) -> None: ...
    def __eq__(self, span): ...
    def __ne__(self, span): ...
    def __lt__(self, span): ...
    def __gt__(self, span): ...
    def __hash__(self): ...
    @classmethod
    def merge(cls, spans): ...
    def to(self, span): ...
    def overlaps(self, span): ...
    def surrounds(self, span): ...
    def is_within(self, span): ...
    def is_before(self, span): ...
    def is_after(self, span): ...
    def touches(self, span): ...
    def distance_to(self, span): ...

def bisect_spans(spans, start): ...

class SpanWrappingMatcher(wrappers.WrappingMatcher):
    def __init__(self, child) -> None: ...
    def copy(self): ...
    def spans(self): ...
    def next(self) -> None: ...
    def skip_to(self, id) -> None: ...
    def all_ids(self) -> Generator[Incomplete]: ...

class SpanBiMatcher(SpanWrappingMatcher):
    def copy(self): ...
    def depth(self): ...
    def replace(self, minquality: int = 0): ...

class SpanQuery(Query):
    def __eq__(self, other): ...
    def __hash__(self): ...
    def field(self) -> None: ...
    def needs_spans(self): ...

class WrappingSpan(SpanQuery):
    def is_leaf(self): ...
    def apply(self, fn): ...
    def field(self): ...

class SpanFirst(WrappingSpan):
    q: Incomplete
    limit: Incomplete
    def __init__(self, q, limit: int = 0) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    class SpanFirstMatcher(SpanWrappingMatcher):
        limit: Incomplete
        def __init__(self, child, limit: int = 0) -> None: ...
        def copy(self): ...

class SpanNear(SpanQuery):
    q: Incomplete
    a: Incomplete
    b: Incomplete
    slop: Incomplete
    ordered: Incomplete
    mindist: Incomplete
    def __init__(self, a, b, slop: int = 1, ordered: bool = True, mindist: int = 1) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def is_leaf(self): ...
    def apply(self, fn): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    @classmethod
    def phrase(cls, fieldname, words, slop: int = 1, ordered: bool = True): ...
    class SpanNearMatcher(SpanWrappingMatcher):
        a: Incomplete
        b: Incomplete
        slop: Incomplete
        ordered: Incomplete
        mindist: Incomplete
        def __init__(self, a, b, slop: int = 1, ordered: bool = True, mindist: int = 1) -> None: ...
        def copy(self): ...
        def replace(self, minquality: int = 0): ...

class SpanNear2(SpanQuery):
    qs: Incomplete
    slop: Incomplete
    ordered: Incomplete
    mindist: Incomplete
    def __init__(self, qs, slop: int = 1, ordered: bool = True, mindist: int = 1) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def is_leaf(self): ...
    def children(self): ...
    def apply(self, fn): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    class SpanNear2Matcher(SpanWrappingMatcher):
        ms: Incomplete
        slop: Incomplete
        ordered: Incomplete
        mindist: Incomplete
        def __init__(self, ms, slop: int = 1, ordered: bool = True, mindist: int = 1) -> None: ...
        def copy(self): ...
        def replace(self, minquality: int = 0): ...

class SpanOr(SpanQuery):
    q: Incomplete
    subqs: Incomplete
    def __init__(self, subqs) -> None: ...
    def is_leaf(self): ...
    def apply(self, fn): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
    class SpanOrMatcher(SpanBiMatcher):
        a: Incomplete
        b: Incomplete
        def __init__(self, a, b) -> None: ...

class SpanBiQuery(SpanQuery):
    def is_leaf(self): ...
    def apply(self, fn): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class SpanNot(SpanBiQuery):
    q: Incomplete
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    class _Matcher(SpanBiMatcher):
        a: Incomplete
        b: Incomplete
        def __init__(self, a, b) -> None: ...

class SpanContains(SpanBiQuery):
    q: Incomplete
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    class _Matcher(SpanBiMatcher):
        a: Incomplete
        b: Incomplete
        def __init__(self, a, b) -> None: ...

class SpanBefore(SpanBiQuery):
    a: Incomplete
    b: Incomplete
    q: Incomplete
    def __init__(self, a, b) -> None: ...
    class _Matcher(SpanBiMatcher):
        a: Incomplete
        b: Incomplete
        def __init__(self, a, b) -> None: ...

class SpanCondition(SpanBiQuery):
    a: Incomplete
    b: Incomplete
    q: Incomplete
    def __init__(self, a, b) -> None: ...
    class _Matcher(SpanBiMatcher):
        a: Incomplete
        def __init__(self, a, b) -> None: ...
