from _typeshed import Incomplete
from collections import defaultdict as defaultdict
from collections.abc import Generator
from whoosh import matching as matching
from whoosh.analysis import Token as Token
from whoosh.compat import bytes_type as bytes_type, text_type as text_type, u as u
from whoosh.lang.morph_en import variations as variations
from whoosh.query import qcore as qcore

class Term(qcore.Query):
    __inittypes__: Incomplete
    fieldname: Incomplete
    text: Incomplete
    boost: Incomplete
    minquality: Incomplete
    def __init__(self, fieldname, text, boost: float = 1.0, minquality: Incomplete | None = None) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def has_terms(self): ...
    def tokens(self, boost: float = 1.0) -> Generator[Incomplete]: ...  # type: ignore[override]
    def terms(self, phrases: bool = False) -> Generator[Incomplete]: ...
    def replace(self, fieldname, oldtext, newtext): ...
    def estimate_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class MultiTerm(qcore.Query):
    constantscore: bool
    def expanded_terms(self, ixreader, phrases: bool = False) -> Generator[Incomplete]: ...
    def tokens(self, boost: float = 1.0, exreader: Incomplete | None = None) -> Generator[Incomplete]: ...
    def simplify(self, ixreader): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class PatternQuery(MultiTerm):
    __inittypes__: Incomplete
    fieldname: Incomplete
    text: Incomplete
    boost: Incomplete
    constantscore: Incomplete
    def __init__(self, fieldname, text, boost: float = 1.0, constantscore: bool = True) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...

class Prefix(PatternQuery):
    def __unicode__(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class Wildcard(PatternQuery):
    SPECIAL_CHARS: Incomplete
    def __unicode__(self): ...
    def normalize(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class Regex(PatternQuery):
    SPECIAL_CHARS: Incomplete
    def __unicode__(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class ExpandingTerm(MultiTerm):
    def has_terms(self): ...
    def terms(self, phrases: bool = False) -> Generator[Incomplete]: ...

class FuzzyTerm(ExpandingTerm):
    __inittypes__: Incomplete
    fieldname: Incomplete
    text: Incomplete
    boost: Incomplete
    maxdist: Incomplete
    prefixlength: Incomplete
    constantscore: Incomplete
    def __init__(self, fieldname, text, boost: float = 1.0, maxdist: int = 1, prefixlength: int = 1, constantscore: bool = True) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def replace(self, fieldname, oldtext, newtext): ...

class Variations(ExpandingTerm):
    fieldname: Incomplete
    text: Incomplete
    boost: Incomplete
    def __init__(self, fieldname, text, boost: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __unicode__(self): ...
    def replace(self, fieldname, oldtext, newtext): ...
