from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import matching as matching
from whoosh.compat import text_type as text_type, u as u, xrange as xrange
from whoosh.query import qcore as qcore

class WrappingQuery(qcore.Query):
    child: Incomplete
    def __init__(self, child) -> None: ...
    def __hash__(self): ...
    def is_leaf(self): ...
    def children(self) -> Generator[Incomplete]: ...
    def apply(self, fn): ...
    def requires(self): ...
    def field(self): ...
    def with_boost(self, boost): ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class Not(qcore.Query):
    __inittypes__: Incomplete
    query: Incomplete
    boost: Incomplete
    def __init__(self, query, boost: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __unicode__(self): ...
    def __hash__(self): ...
    def is_leaf(self): ...
    def children(self) -> Generator[Incomplete]: ...
    def apply(self, fn): ...
    def normalize(self): ...
    def field(self) -> None: ...
    def estimate_size(self, ixreader): ...
    def estimate_min_size(self, ixreader): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class ConstantScoreQuery(WrappingQuery):
    score: Incomplete
    def __init__(self, child, score: float = 1.0) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def matcher(self, searcher, context: Incomplete | None = None): ...

class WeightingQuery(WrappingQuery):
    weighting: Incomplete
    def __init__(self, child, weighting) -> None: ...
    def matcher(self, searcher, context: Incomplete | None = None): ...
