from _typeshed import Incomplete
from whoosh.compat import BytesIO as BytesIO, memoryview_ as memoryview_
from whoosh.filedb.filestore import FileStorage as FileStorage, StorageError as StorageError
from whoosh.filedb.structfile import BufferFile as BufferFile, StructFile as StructFile
from whoosh.system import emptybytes as emptybytes
from whoosh.util import random_name as random_name

class CompoundStorage(FileStorage):
    readonly: bool
    is_closed: bool
    def __init__(self, dbfile, use_mmap: bool = True, basepos: int = 0) -> None: ...
    def close(self) -> None: ...
    def range(self, name): ...
    def open_file(self, name, *args, **kwargs): ...
    def list(self): ...
    def file_exists(self, name): ...
    def file_length(self, name): ...
    def file_modified(self, name): ...
    def lock(self, name): ...
    @staticmethod
    def assemble(dbfile, store, names, **options) -> None: ...
    @staticmethod
    def write_dir(dbfile, basepos, directory, options: Incomplete | None = None) -> None: ...

class SubFile:
    name: Incomplete
    closed: bool
    def __init__(self, parentfile, offset, length, name: Incomplete | None = None) -> None: ...
    def close(self) -> None: ...
    def subset(self, position, length, name: Incomplete | None = None): ...
    def read(self, size: Incomplete | None = None): ...
    def readline(self): ...
    def seek(self, where, whence: int = 0) -> None: ...
    def tell(self): ...

class CompoundWriter:
    def __init__(self, tempstorage, buffersize=...) -> None: ...
    def create_file(self, name): ...
    def save_as_compound(self, dbfile) -> None: ...
    def save_as_files(self, storage, name_fn) -> None: ...
    class SubStream:
        blocks: Incomplete
        def __init__(self, dbfile, buffersize) -> None: ...
        def tell(self): ...
        def write(self, inbytes) -> None: ...
        def close(self) -> None: ...
