import types
from _typeshed import Incomplete
from whoosh.compat import BytesIO as BytesIO, memoryview_ as memoryview_
from whoosh.filedb.structfile import BufferFile as BufferFile, StructFile as StructFile
from whoosh.index import EmptyIndexError as EmptyIndexError
from whoosh.util import random_name as random_name
from whoosh.util.filelock import FileLock as FileLock

class StorageError(Exception): ...
class ReadOnlyError(StorageError): ...

class Storage:
    readonly: bool
    supports_mmap: bool
    def __iter__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def create(self): ...
    def destroy(self, *args, **kwargs) -> None: ...
    def create_index(self, schema, indexname=..., indexclass: Incomplete | None = None): ...
    def open_index(self, indexname=..., schema: Incomplete | None = None, indexclass: Incomplete | None = None): ...
    def index_exists(self, indexname: Incomplete | None = None): ...
    def create_file(self, name) -> None: ...
    def open_file(self, name, *args, **kwargs) -> None: ...
    def list(self) -> None: ...
    def file_exists(self, name) -> None: ...
    def file_modified(self, name) -> None: ...
    def file_length(self, name) -> None: ...
    def delete_file(self, name) -> None: ...
    def rename_file(self, frm, to, safe: bool = False) -> None: ...
    def lock(self, name) -> None: ...
    def close(self) -> None: ...
    def optimize(self) -> None: ...
    def temp_storage(self, name: Incomplete | None = None) -> None: ...

class OverlayStorage(Storage):
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    def create_index(self, *args, **kwargs) -> None: ...
    def open_index(self, *args, **kwargs) -> None: ...
    def create_file(self, *args, **kwargs): ...
    def open_file(self, name, *args, **kwargs): ...
    def list(self): ...
    def file_exists(self, name): ...
    def file_modified(self, name): ...
    def file_length(self, name): ...
    def delete_file(self, name): ...
    def rename_file(self, *args, **kwargs) -> None: ...
    def lock(self, name): ...
    def close(self) -> None: ...
    def optimize(self) -> None: ...
    def temp_storage(self, name: Incomplete | None = None): ...

class FileStorage(Storage):
    supports_mmap: bool
    folder: Incomplete
    readonly: Incomplete
    locks: Incomplete
    def __init__(self, path, supports_mmap: bool = True, readonly: bool = False, debug: bool = False) -> None: ...
    def create(self): ...
    def destroy(self) -> None: ...
    def create_file(self, name, excl: bool = False, mode: str = 'wb', **kwargs): ...
    def open_file(self, name, **kwargs): ...
    def clean(self, ignore: bool = False) -> None: ...
    def list(self): ...
    def file_exists(self, name): ...
    def file_modified(self, name): ...
    def file_length(self, name): ...
    def delete_file(self, name) -> None: ...
    def rename_file(self, oldname, newname, safe: bool = False) -> None: ...
    def lock(self, name): ...
    def temp_storage(self, name: Incomplete | None = None): ...

class RamStorage(Storage):
    supports_mmap: bool
    files: Incomplete
    locks: Incomplete
    folder: str
    def __init__(self) -> None: ...
    def destroy(self) -> None: ...
    def list(self): ...
    def clean(self) -> None: ...
    def total_size(self): ...
    def file_exists(self, name): ...
    def file_length(self, name): ...
    def file_modified(self, name): ...
    def delete_file(self, name) -> None: ...
    def rename_file(self, name, newname, safe: bool = False) -> None: ...
    def create_file(self, name, **kwargs): ...
    def open_file(self, name, **kwargs): ...
    def lock(self, name): ...
    def temp_storage(self, name: Incomplete | None = None): ...

def copy_storage(sourcestore, deststore) -> None: ...
def copy_to_ram(storage): ...
