from _typeshed import Incomplete
from bisect import bisect_left as bisect_left
from collections.abc import Generator
from whoosh.compat import b as b, bytes_type as bytes_type, xrange as xrange
from whoosh.system import emptybytes as emptybytes
from whoosh.util.numlists import GrowableArray as GrowableArray

class FileFormatError(Exception): ...

def cdb_hash(key): ...
def md5_hash(key): ...
def crc_hash(key): ...

class HashWriter:
    dbfile: Incomplete
    hashtype: Incomplete
    hashfn: Incomplete
    extras: Incomplete
    startoffset: Incomplete
    buckets: Incomplete
    directory: Incomplete
    def __init__(self, dbfile, magic=..., hashtype: int = 0) -> None: ...
    def tell(self): ...
    def add(self, key, value) -> None: ...
    def add_all(self, items) -> None: ...
    def close(self): ...

class HashReader:
    dbfile: Incomplete
    startoffset: Incomplete
    is_closed: bool
    hashtype: Incomplete
    hashfn: Incomplete
    startofdata: Incomplete
    tables: Incomplete
    endofdata: Incomplete
    def __init__(self, dbfile, length: Incomplete | None = None, magic=..., startoffset: int = 0) -> None: ...
    @classmethod
    def open(cls, storage, name): ...
    def file(self): ...
    def close(self) -> None: ...
    def key_at(self, pos): ...
    def key_and_range_at(self, pos): ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __contains__(self, key) -> bool: ...
    def keys(self) -> Generator[Incomplete]: ...
    def values(self) -> Generator[Incomplete]: ...
    def items(self) -> Generator[Incomplete]: ...
    def get(self, key, default: Incomplete | None = None): ...
    def all(self, key) -> Generator[Incomplete]: ...
    def ranges_for_key(self, key) -> Generator[Incomplete]: ...
    def range_for_key(self, key): ...

class OrderedHashWriter(HashWriter):
    index: Incomplete
    lastkey: Incomplete
    def __init__(self, dbfile) -> None: ...
    def add(self, key, value) -> None: ...

class OrderedHashReader(HashReader):
    def closest_key(self, key): ...
    def ranges_from(self, key) -> Generator[Incomplete]: ...
    def keys_from(self, key) -> Generator[Incomplete]: ...
    def items_from(self, key) -> Generator[Incomplete]: ...
    def closest_key_pos(self, key): ...

class FieldedOrderedHashWriter(HashWriter):
    fieldmap: Incomplete
    lastkey: Incomplete
    def __init__(self, dbfile) -> None: ...
    fieldstart: Incomplete
    fieldname: Incomplete
    poses: Incomplete
    def start_field(self, fieldname) -> None: ...
    def add(self, key, value) -> None: ...
    def end_field(self) -> None: ...

class FieldedOrderedHashReader(HashReader):
    fieldmap: Incomplete
    fieldlist: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def field_start(self, fieldname): ...
    def fielded_ranges(self, pos: Incomplete | None = None, eod: Incomplete | None = None) -> Generator[Incomplete]: ...
    def iter_terms(self) -> Generator[Incomplete]: ...
    def iter_term_items(self) -> Generator[Incomplete]: ...
    def contains_term(self, fieldname, btext): ...
    def range_for_term(self, fieldname, btext): ...
    def term_data(self, fieldname, btext): ...
    def term_get(self, fieldname, btext, default: Incomplete | None = None): ...
    def closest_term_pos(self, fieldname, key): ...
    def closest_term(self, fieldname, btext): ...
    def term_ranges_from(self, fieldname, btext) -> Generator[Incomplete]: ...
    def terms_from(self, fieldname, btext) -> Generator[Incomplete]: ...
    def term_items_from(self, fieldname, btext) -> Generator[Incomplete]: ...
