from _typeshed import Incomplete
from google.appengine.ext import db
from whoosh.compat import BytesIO as BytesIO
from whoosh.filedb.filestore import ReadOnlyError as ReadOnlyError, Storage as Storage
from whoosh.filedb.structfile import StructFile as StructFile
from whoosh.index import FileIndex as FileIndex, TOC as TOC

class DatastoreFile(db.Model):
    value: Incomplete
    mtime: Incomplete
    data: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def loadfile(cls, name): ...
    def close(self) -> None: ...
    def tell(self): ...
    def write(self, data): ...
    def read(self, length): ...
    def seek(self, *args): ...
    def readline(self): ...
    def getvalue(self): ...

class MemcacheLock:
    name: Incomplete
    def __init__(self, name) -> None: ...
    def acquire(self, blocking: bool = False): ...
    def release(self) -> None: ...

class DatastoreStorage(Storage):
    def create_index(self, schema, indexname=...): ...
    def open_index(self, indexname=..., schema: Incomplete | None = None): ...
    def list(self): ...
    def clean(self) -> None: ...
    def total_size(self): ...
    def file_exists(self, name): ...
    def file_modified(self, name): ...
    def file_length(self, name): ...
    def delete_file(self, name): ...
    def rename_file(self, name, newname, safe: bool = False) -> None: ...
    def create_file(self, name, **kwargs): ...
    def open_file(self, name, *args, **kwargs): ...
    def lock(self, name): ...
    def temp_storage(self, name: Incomplete | None = None): ...
