import types
from _typeshed import Incomplete
from whoosh.compat import BytesIO as BytesIO, array_frombytes as array_frombytes, array_tobytes as array_tobytes, bytes_type as bytes_type
from whoosh.system import IS_LITTLE as IS_LITTLE, pack_byte as pack_byte, pack_float as pack_float, pack_int as pack_int, pack_long as pack_long, pack_sbyte as pack_sbyte, pack_uint as pack_uint, pack_uint_le as pack_uint_le, pack_ulong as pack_ulong, pack_ushort as pack_ushort, pack_ushort_le as pack_ushort_le, unpack_byte as unpack_byte, unpack_float as unpack_float, unpack_int as unpack_int, unpack_long as unpack_long, unpack_sbyte as unpack_sbyte, unpack_uint as unpack_uint, unpack_uint_le as unpack_uint_le, unpack_ulong as unpack_ulong, unpack_ushort as unpack_ushort, unpack_ushort_le as unpack_ushort_le
from whoosh.util.varints import decode_signed_varint as decode_signed_varint, read_varint as read_varint, signed_varint as signed_varint, varint as varint

class StructFile:
    file: Incomplete
    onclose: Incomplete
    is_closed: bool
    is_real: Incomplete
    fileno: Incomplete
    def __init__(self, fileobj, name: Incomplete | None = None, onclose: Incomplete | None = None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def __iter__(self): ...
    def raw_file(self): ...
    def read(self, *args, **kwargs): ...
    def readline(self, *args, **kwargs): ...
    def write(self, *args, **kwargs): ...
    def tell(self, *args, **kwargs): ...
    def seek(self, *args, **kwargs): ...
    def truncate(self, *args, **kwargs): ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def subset(self, offset, length, name: Incomplete | None = None): ...
    def write_string(self, s) -> None: ...
    def write_string2(self, s) -> None: ...
    def write_string4(self, s) -> None: ...
    def read_string(self): ...
    def read_string2(self): ...
    def read_string4(self): ...
    def get_string2(self, pos): ...
    def get_string4(self, pos): ...
    def skip_string(self) -> None: ...
    def write_varint(self, i) -> None: ...
    def write_svarint(self, i) -> None: ...
    def read_varint(self): ...
    def read_svarint(self): ...
    def write_tagint(self, i) -> None: ...
    def read_tagint(self): ...
    def write_byte(self, n) -> None: ...
    def read_byte(self): ...
    def write_pickle(self, obj, protocol: int = -1) -> None: ...
    def read_pickle(self): ...
    def write_sbyte(self, n) -> None: ...
    def write_int(self, n) -> None: ...
    def write_uint(self, n) -> None: ...
    def write_uint_le(self, n) -> None: ...
    def write_ushort(self, n) -> None: ...
    def write_ushort_le(self, n) -> None: ...
    def write_long(self, n) -> None: ...
    def write_ulong(self, n) -> None: ...
    def write_float(self, n) -> None: ...
    def write_array(self, arry) -> None: ...
    def read_sbyte(self): ...
    def read_int(self): ...
    def read_uint(self): ...
    def read_uint_le(self): ...
    def read_ushort(self): ...
    def read_ushort_le(self): ...
    def read_long(self): ...
    def read_ulong(self): ...
    def read_float(self): ...
    def read_array(self, typecode, length): ...
    def get(self, position, length): ...
    def get_byte(self, position): ...
    def get_sbyte(self, position): ...
    def get_int(self, position): ...
    def get_uint(self, position): ...
    def get_ushort(self, position): ...
    def get_long(self, position): ...
    def get_ulong(self, position): ...
    def get_float(self, position): ...
    def get_array(self, position, typecode, length): ...

class BufferFile(StructFile):
    file: Incomplete
    onclose: Incomplete
    is_real: bool
    is_closed: bool
    def __init__(self, buf, name: Incomplete | None = None, onclose: Incomplete | None = None) -> None: ...
    def subset(self, position, length, name: Incomplete | None = None): ...
    def get(self, position, length): ...
    def get_array(self, position, typecode, length): ...

class ChecksumFile(StructFile):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def seek(self, *args) -> None: ...
    def read(self, *args, **kwargs): ...
    def write(self, b) -> None: ...
    def checksum(self): ...
