from _typeshed import Incomplete
from whoosh.compat import xrange as xrange

b85chars: str
b85dec: Incomplete

def to_base85(x, islong: bool = False): ...
def from_base85(text): ...
def b85encode(text, pad: bool = False): ...
def b85decode(text): ...
