from _typeshed import Incomplete
from collections.abc import Generator
from persistent import Persistent
from whoosh import index as index, qparser as qparser, query as query, scoring as scoring
from whoosh.util import find_object as find_object, now as now

class ZDoc(Persistent):
    def __init__(self, d) -> None: ...

class Module:
    bench: Incomplete
    options: Incomplete
    args: Incomplete
    def __init__(self, bench, options, args) -> None: ...
    def indexer(self, **kwargs) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, **kwargs) -> None: ...
    def searcher(self) -> None: ...
    def query(self) -> None: ...
    def find(self, q) -> None: ...
    def findterms(self, terms) -> None: ...
    def results(self, r) -> Generator[Incomplete]: ...

class Spec:
    headline_field: str
    main_field: str
    options: Incomplete
    args: Incomplete
    def __init__(self, options, args) -> None: ...
    def documents(self) -> None: ...
    def setup(self) -> None: ...
    def print_results(self, ls) -> None: ...

class WhooshModule(Module):
    writer: Incomplete
    def indexer(self, create: bool = True) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, merge: bool = True, optimize: bool = False) -> None: ...
    srch: Incomplete
    parser: Incomplete
    def searcher(self) -> None: ...
    def query(self): ...
    def find(self, q): ...
    def findterms(self, terms) -> Generator[Incomplete]: ...

class XappyModule(Module):
    def indexer(self, **kwargs): ...
    def index_document(self, conn, d) -> None: ...
    def finish(self, conn) -> None: ...
    def searcher(self): ...
    def query(self, conn): ...
    def find(self, conn, q): ...
    def findterms(self, conn, terms) -> Generator[Incomplete]: ...
    def results(self, r) -> Generator[Incomplete]: ...

class XapianModule(Module):
    database: Incomplete
    ixer: Incomplete
    def indexer(self, **kwargs) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, **kwargs) -> None: ...
    db: Incomplete
    enq: Incomplete
    qp: Incomplete
    def searcher(self) -> None: ...
    def query(self): ...
    def find(self, q): ...
    def findterms(self, terms) -> Generator[Incomplete]: ...
    def results(self, matches) -> Generator[Incomplete]: ...

class SolrModule(Module):
    solr_doclist: Incomplete
    conn: Incomplete
    def indexer(self, **kwargs) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, **kwargs) -> None: ...
    solr: Incomplete
    def searcher(self) -> None: ...
    def query(self): ...
    def find(self, q): ...
    def findterms(self, terms) -> Generator[Incomplete]: ...

class ZcatalogModule(Module):
    cat: Incomplete
    zcatalog_count: int
    def indexer(self, **kwargs) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, **kwargs) -> None: ...
    def searcher(self) -> None: ...
    def query(self): ...
    def find(self, q): ...
    def findterms(self, terms) -> Generator[Incomplete]: ...
    def results(self, r) -> Generator[Incomplete]: ...

class NucularModule(Module):
    archive: Incomplete
    count: int
    def indexer(self, create: bool = True) -> None: ...
    def index_document(self, d) -> None: ...
    def finish(self, **kwargs) -> None: ...
    def searcher(self) -> None: ...
    def query(self): ...
    def find(self, q): ...
    def findterms(self, terms) -> Generator[Incomplete]: ...

class Bench:
    libs: Incomplete
    def index(self, lib) -> None: ...
    def search(self, lib) -> None: ...
    def search_file(self, lib) -> None: ...
    options: Incomplete
    args: Incomplete
    spec: Incomplete
    def run(self, specclass) -> None: ...
