from _typeshed import Incomplete
from whoosh.compat import xrange as xrange

def levenshtein(seq1, seq2, limit: Incomplete | None = None): ...
def damerau_levenshtein(seq1, seq2, limit: Incomplete | None = None): ...
def relative(a, b): ...
distance = damerau_levenshtein
