import abc
from _typeshed import Incomplete
from whoosh.matching import mcore as mcore

class BiMatcher(mcore.Matcher, metaclass=abc.ABCMeta):
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    def reset(self) -> None: ...
    def children(self): ...
    def copy(self): ...
    def depth(self): ...
    def skip_to(self, id): ...
    def supports_block_quality(self): ...
    def supports(self, astype): ...

class AdditiveBiMatcher(BiMatcher, metaclass=abc.ABCMeta):
    def max_quality(self): ...
    def block_quality(self): ...
    def weight(self): ...
    def score(self): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...

class UnionMatcher(AdditiveBiMatcher, metaclass=abc.ABCMeta):
    def replace(self, minquality: int = 0): ...
    def is_active(self): ...
    def skip_to(self, id): ...
    def id(self): ...
    def next(self): ...
    def spans(self): ...
    def weight(self): ...
    def score(self): ...
    def skip_to_quality(self, minquality): ...

class DisjunctionMaxMatcher(UnionMatcher, metaclass=abc.ABCMeta):
    tiebreak: Incomplete
    def __init__(self, a, b, tiebreak: float = 0.0) -> None: ...
    def copy(self): ...
    def replace(self, minquality: int = 0): ...
    def score(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality): ...

class IntersectionMatcher(AdditiveBiMatcher, metaclass=abc.ABCMeta):
    def __init__(self, a, b) -> None: ...
    def reset(self) -> None: ...
    def replace(self, minquality: int = 0): ...
    def is_active(self): ...
    def id(self): ...
    def all_ids(self): ...
    def skip_to(self, id): ...
    def skip_to_quality(self, minquality): ...
    def next(self): ...
    def spans(self): ...

class AndNotMatcher(BiMatcher):
    def __init__(self, a, b) -> None: ...
    def reset(self) -> None: ...
    def is_active(self): ...
    def supports_block_quality(self): ...
    def replace(self, minquality: int = 0): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality): ...
    def id(self): ...
    def next(self): ...
    def skip_to(self, id) -> None: ...
    def weight(self): ...
    def score(self): ...
    def supports(self, astype): ...
    def value(self): ...
    def value_as(self, astype): ...

class AndMaybeMatcher(AdditiveBiMatcher):
    def __init__(self, a, b) -> None: ...
    def reset(self) -> None: ...
    def is_active(self): ...
    def id(self): ...
    def next(self): ...
    def skip_to(self, id): ...
    def replace(self, minquality: int = 0): ...
    def skip_to_quality(self, minquality): ...
    def weight(self): ...
    def score(self): ...
    def supports(self, astype): ...
    def value(self): ...
    def value_as(self, astype): ...
