import abc
from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import xrange as xrange
from whoosh.matching import mcore as mcore

class CombinationMatcher(mcore.Matcher, metaclass=abc.ABCMeta):
    def __init__(self, submatchers, boost: float = 1.0) -> None: ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def supports(self, astype): ...
    def children(self): ...
    def score(self): ...

class PreloadedUnionMatcher(CombinationMatcher, metaclass=abc.ABCMeta):
    def __init__(self, submatchers, doccount, boost: float = 1.0, scored: bool = True) -> None: ...
    def is_active(self): ...
    def id(self): ...
    def score(self): ...
    def next(self) -> None: ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to(self, docnum) -> None: ...
    def skip_to_quality(self, minquality): ...
    def supports(self, astype): ...
    def all_ids(self) -> Generator[Incomplete]: ...

class ArrayUnionMatcher(CombinationMatcher, metaclass=abc.ABCMeta):
    def __init__(self, submatchers, doccount, boost: float = 1.0, scored: bool = True, partsize: int = 2048) -> None: ...
    def supports(self, astype): ...
    def is_active(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to(self, docnum) -> None: ...
    def skip_to_quality(self, minquality): ...
    def id(self): ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def next(self): ...
    def score(self): ...
