import abc
from _typeshed import Incomplete
from abc import abstractmethod
from collections.abc import Generator
from whoosh.compat import izip, xrange

class ReadTooFar(Exception): ...
class NoQualityAvailable(Exception): ...

class Matcher(metaclass=abc.ABCMeta):
    @abstractmethod
    def is_active(self): ...
    @abstractmethod
    def reset(self): ...
    def term(self) -> None: ...
    def term_matchers(self) -> Generator[Incomplete]: ...
    def matching_terms(self, id: Incomplete | None = None) -> Generator[Incomplete]: ...
    def is_leaf(self): ...
    def children(self): ...
    def replace(self, minquality: int = 0): ...
    @abstractmethod
    def copy(self): ...
    def depth(self): ...
    def supports_block_quality(self): ...
    def max_quality(self) -> None: ...
    def block_quality(self) -> None: ...
    @abstractmethod
    def id(self): ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def all_items(self) -> Generator[Incomplete]: ...
    def items_as(self, astype) -> Generator[Incomplete]: ...
    @abstractmethod
    def value(self): ...
    @abstractmethod
    def supports(self, astype): ...
    @abstractmethod
    def value_as(self, astype): ...
    def spans(self): ...
    def skip_to(self, id) -> None: ...
    def skip_to_quality(self, minquality) -> None: ...
    @abstractmethod
    def next(self): ...
    def weight(self): ...
    @abstractmethod
    def score(self): ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...

class ConstantScoreMatcher(Matcher, metaclass=abc.ABCMeta):
    def __init__(self, score: float = 1.0) -> None: ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality) -> None: ...
    def score(self): ...

class NullMatcherClass(Matcher, metaclass=abc.ABCMeta):
    def __call__(self): ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality): ...
    def is_active(self): ...
    def reset(self) -> None: ...
    def all_ids(self): ...
    def copy(self): ...

NullMatcher: Incomplete

class ListMatcher(Matcher):
    def __init__(self, ids, weights: Incomplete | None = None, values: Incomplete | None = None, format: Incomplete | None = None, scorer: Incomplete | None = None, position: int = 0, all_weights: Incomplete | None = None, term: Incomplete | None = None, terminfo: Incomplete | None = None) -> None: ...
    def is_active(self): ...
    def reset(self) -> None: ...
    def skip_to(self, id) -> None: ...
    def term(self): ...
    def copy(self): ...
    def replace(self, minquality: int = 0): ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality): ...
    def id(self): ...
    def all_ids(self): ...
    def all_items(self): ...
    def value(self): ...
    def value_as(self, astype): ...
    def supports(self, astype): ...
    def next(self) -> None: ...
    def weight(self): ...
    def block_min_length(self): ...
    def block_max_length(self): ...
    def block_max_weight(self): ...
    def score(self): ...

class LeafMatcher(Matcher, metaclass=abc.ABCMeta):
    def term(self): ...
    def items_as(self, astype) -> Generator[Incomplete]: ...
    def supports(self, astype): ...
    def value_as(self, astype): ...
    def spans(self): ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def score(self): ...
