from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import xrange as xrange
from whoosh.matching import mcore as mcore

class WrappingMatcher(mcore.Matcher):
    child: Incomplete
    boost: Incomplete
    def __init__(self, child, boost: float = 1.0) -> None: ...
    def copy(self): ...
    def depth(self): ...
    def replace(self, minquality: int = 0): ...
    def id(self): ...
    def all_ids(self): ...
    def is_active(self): ...
    def reset(self) -> None: ...
    def children(self): ...
    def supports(self, astype): ...
    def value(self): ...
    def value_as(self, astype): ...
    def spans(self): ...
    def skip_to(self, id): ...
    def next(self) -> None: ...
    def supports_block_quality(self): ...
    def skip_to_quality(self, minquality): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def weight(self): ...
    def score(self): ...

class MultiMatcher(mcore.Matcher):
    matchers: Incomplete
    offsets: Incomplete
    scorer: Incomplete
    current: Incomplete
    def __init__(self, matchers, idoffsets, scorer: Incomplete | None = None, current: int = 0) -> None: ...
    def is_active(self): ...
    def reset(self) -> None: ...
    def children(self): ...
    def copy(self): ...
    def depth(self): ...
    def replace(self, minquality: int = 0): ...
    def id(self): ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def spans(self): ...
    def supports(self, astype): ...
    def value(self): ...
    def value_as(self, astype): ...
    def next(self) -> None: ...
    def skip_to(self, id): ...
    def supports_block_quality(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def weight(self): ...
    def score(self): ...

def ExcludeMatcher(child, excluded, boost: float = 1.0): ...

class FilterMatcher(WrappingMatcher):
    boost: Incomplete
    def __init__(self, child, ids, exclude: bool = False, boost: float = 1.0) -> None: ...
    def reset(self) -> None: ...
    def copy(self): ...
    def next(self) -> None: ...
    def skip_to(self, id) -> None: ...
    def all_ids(self): ...
    def all_items(self): ...

class InverseMatcher(WrappingMatcher):
    limit: Incomplete
    missing: Incomplete
    def __init__(self, child, limit, missing: Incomplete | None = None, weight: float = 1.0, id: int = 0) -> None: ...
    def copy(self): ...
    def is_active(self): ...
    def reset(self) -> None: ...
    def supports_block_quality(self): ...
    def id(self): ...
    def all_ids(self): ...
    def next(self) -> None: ...
    def skip_to(self, id) -> None: ...
    def weight(self): ...
    def score(self): ...

class RequireMatcher(WrappingMatcher):
    a: Incomplete
    b: Incomplete
    def __init__(self, a, b) -> None: ...
    def copy(self): ...
    def supports_block_quality(self): ...
    def replace(self, minquality: int = 0): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def skip_to_quality(self, minquality): ...
    def weight(self): ...
    def score(self): ...
    def supports(self, astype): ...
    def value(self): ...
    def value_as(self, astype): ...

class ConstantScoreWrapperMatcher(WrappingMatcher):
    def __init__(self, child, score: float = 1.0) -> None: ...
    def copy(self): ...
    def max_quality(self): ...
    def block_quality(self): ...
    def score(self): ...

class SingleTermMatcher(WrappingMatcher):
    def __init__(self, child, term) -> None: ...
    def term(self): ...
    def replace(self, minquality: int = 0): ...

class CoordMatcher(WrappingMatcher):
    def __init__(self, child, scale: float = 1.0) -> None: ...
    def max_quality(self): ...
    def block_quality(self): ...
    def score(self): ...
