from _typeshed import Incomplete
from whoosh.compat import iteritems as iteritems, xrange as xrange

class ExpansionModel:
    N: Incomplete
    collection_total: Incomplete
    mean_length: Incomplete
    def __init__(self, doc_count, field_length) -> None: ...
    def normalizer(self, maxweight, top_total) -> None: ...
    def score(self, weight_in_top, weight_in_collection, top_total) -> None: ...

class Bo1Model(ExpansionModel):
    def normalizer(self, maxweight, top_total): ...
    def score(self, weight_in_top, weight_in_collection, top_total): ...

class Bo2Model(ExpansionModel):
    def normalizer(self, maxweight, top_total): ...
    def score(self, weight_in_top, weight_in_collection, top_total): ...

class KLModel(ExpansionModel):
    def normalizer(self, maxweight, top_total): ...
    def score(self, weight_in_top, weight_in_collection, top_total): ...

class Expander:
    ixreader: Incomplete
    fieldname: Incomplete
    model: Incomplete
    topN_weight: Incomplete
    top_total: int
    def __init__(self, ixreader, fieldname, model=...) -> None: ...
    def add(self, vector) -> None: ...
    def add_document(self, docnum) -> None: ...
    def add_text(self, string) -> None: ...
    def expanded_terms(self, number, normalize: bool = True): ...

def shingles(input, size: int = 2): ...
def simhash(features, hashbits: int = 32): ...
def hamming_distance(first_hash, other_hash, hashbits: int = 32): ...
def kmeans(data, k, t: float = 0.0001, distfun: Incomplete | None = None, maxiter: int = 50, centers: Incomplete | None = None): ...
def two_pass_variance(data): ...
def weighted_incremental_variance(data_weight_pairs): ...
def swin(data, size): ...
