import abc
from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import sorting as sorting
from whoosh.compat import abstractmethod as abstractmethod, iteritems as iteritems, itervalues as itervalues, xrange as xrange
from whoosh.searching import Results as Results, TimeLimit as TimeLimit
from whoosh.util import now as now

def ilen(iterator): ...

class Collector(metaclass=abc.ABCMeta):
    top_searcher: Incomplete
    q: Incomplete
    context: Incomplete
    starttime: Incomplete
    runtime: Incomplete
    docset: Incomplete
    def prepare(self, top_searcher, q, context) -> None: ...
    def run(self) -> None: ...
    subsearcher: Incomplete
    offset: Incomplete
    matcher: Incomplete
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def computes_count(self): ...
    def all_ids(self): ...
    def count(self): ...
    def collect_matches(self) -> None: ...
    @abstractmethod
    def collect(self, sub_docnum): ...
    @abstractmethod
    def sort_key(self, sub_docnum): ...
    def remove(self, global_docnum) -> None: ...
    def matches(self): ...
    def finish(self) -> None: ...
    @abstractmethod
    def results(self): ...

class ScoredCollector(Collector, metaclass=abc.ABCMeta):
    replace: Incomplete
    def __init__(self, replace: int = 10) -> None: ...
    final_fn: Incomplete
    items: Incomplete
    minscore: int
    replaced_times: int
    skipped_times: int
    def prepare(self, top_searcher, q, context) -> None: ...
    def sort_key(self, sub_docnum): ...
    def collect(self, sub_docnum): ...
    matcher: Incomplete
    def matches(self) -> Generator[Incomplete]: ...

class TopCollector(ScoredCollector):
    limit: Incomplete
    usequality: Incomplete
    total: int
    def __init__(self, limit: int = 10, usequality: bool = True, **kwargs) -> None: ...
    def computes_count(self): ...
    def all_ids(self): ...
    def count(self): ...
    minscore: Incomplete
    def remove(self, global_docnum) -> None: ...
    def results(self): ...

class UnlimitedCollector(ScoredCollector):
    reverse: Incomplete
    def __init__(self, reverse: bool = False) -> None: ...
    def results(self): ...

class SortingCollector(Collector):
    sortfacet: Incomplete
    limit: Incomplete
    reverse: Incomplete
    def __init__(self, sortedby, limit: int = 10, reverse: bool = False) -> None: ...
    categorizer: Incomplete
    items: Incomplete
    def prepare(self, top_searcher, q, context) -> None: ...
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def sort_key(self, sub_docnum): ...
    def collect(self, sub_docnum): ...
    def results(self): ...

class UnsortedCollector(Collector, metaclass=abc.ABCMeta):
    items: Incomplete
    def prepare(self, top_searcher, q, context) -> None: ...
    def collect(self, sub_docnum) -> None: ...
    def results(self): ...

class WrappingCollector(Collector):
    child: Incomplete
    def __init__(self, child) -> None: ...
    @property
    def top_searcher(self): ...
    @property
    def context(self): ...
    def prepare(self, top_searcher, q, context) -> None: ...
    subsearcher: Incomplete
    matcher: Incomplete
    offset: Incomplete
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def all_ids(self): ...
    def count(self): ...
    def collect_matches(self) -> None: ...
    def sort_key(self, sub_docnum): ...
    def collect(self, sub_docnum): ...
    def remove(self, global_docnum): ...
    def matches(self): ...
    def finish(self) -> None: ...
    def results(self): ...

class FilterCollector(WrappingCollector):
    child: Incomplete
    allow: Incomplete
    restrict: Incomplete
    def __init__(self, child, allow: Incomplete | None = None, restrict: Incomplete | None = None) -> None: ...
    filtered_count: int
    def prepare(self, top_searcher, q, context) -> None: ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def count(self): ...
    def collect_matches(self) -> None: ...
    def results(self): ...

class FacetCollector(WrappingCollector):
    child: Incomplete
    facets: Incomplete
    maptype: Incomplete
    def __init__(self, child, groupedby, maptype: Incomplete | None = None) -> None: ...
    facetmaps: Incomplete
    categorizers: Incomplete
    def prepare(self, top_searcher, q, context) -> None: ...
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def collect(self, sub_docnum): ...
    def results(self): ...

class CollapseCollector(WrappingCollector):
    child: Incomplete
    keyfacet: Incomplete
    limit: Incomplete
    orderfacet: Incomplete
    def __init__(self, child, keyfacet, limit: int = 1, order: Incomplete | None = None) -> None: ...
    keyer: Incomplete
    orderer: Incomplete
    lists: Incomplete
    collapsed_counts: Incomplete
    collapsed_total: int
    def prepare(self, top_searcher, q, context) -> None: ...
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def all_ids(self) -> Generator[Incomplete]: ...
    def count(self): ...
    def collect_matches(self) -> None: ...
    def results(self): ...

class TimeLimitCollector(WrappingCollector):
    child: Incomplete
    timelimit: Incomplete
    greedy: Incomplete
    use_alarm: Incomplete
    timer: Incomplete
    timedout: bool
    def __init__(self, child, timelimit, greedy: bool = False, use_alarm: bool = True) -> None: ...
    def prepare(self, top_searcher, q, context) -> None: ...
    def collect_matches(self) -> None: ...
    def finish(self) -> None: ...

class TermsCollector(WrappingCollector):
    child: Incomplete
    settype: Incomplete
    def __init__(self, child, settype=...) -> None: ...
    termdocs: Incomplete
    docterms: Incomplete
    def prepare(self, top_searcher, q, context): ...
    termmatchers: Incomplete
    def set_subsearcher(self, subsearcher, offset) -> None: ...
    def collect(self, sub_docnum) -> None: ...
    def results(self): ...
