from _typeshed import Incomplete
from collections.abc import Generator
from whoosh import analysis as analysis, columns as columns, formats as formats
from whoosh.compat import bytes_type as bytes_type, itervalues as itervalues, string_type as string_type, text_type as text_type, with_metaclass as with_metaclass, xrange as xrange
from whoosh.system import emptybytes as emptybytes, pack_byte as pack_byte, unpack_byte as unpack_byte
from whoosh.util.numeric import NaN as NaN, from_sortable as from_sortable, to_sortable as to_sortable, typecode_max as typecode_max
from whoosh.util.text import utf8decode as utf8decode, utf8encode as utf8encode
from whoosh.util.times import datetime_to_long as datetime_to_long, long_to_datetime as long_to_datetime

class FieldConfigurationError(Exception): ...
class UnknownFieldError(Exception): ...

class FieldType:
    analyzer: Incomplete
    format: Incomplete
    scorable: Incomplete
    stored: Incomplete
    unique: Incomplete
    vector: Incomplete
    indexed: bool
    multitoken_query: str
    sortable_typecode: Incomplete
    column_type: Incomplete
    def __init__(self, format, analyzer, scorable: bool = False, stored: bool = False, unique: bool = False, multitoken_query: str = 'default', sortable: bool = False, vector: Incomplete | None = None) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def index(self, value, **kwargs) -> Generator[Incomplete]: ...
    def tokenize(self, value, **kwargs): ...
    def process_text(self, qstring, mode: str = '', **kwargs): ...
    def to_bytes(self, value): ...
    def to_column_value(self, value): ...
    def from_bytes(self, bs): ...
    def from_column_value(self, value): ...
    def set_sortable(self, sortable) -> None: ...
    def sortable_terms(self, ixreader, fieldname): ...
    def default_column(self): ...
    def self_parsing(self): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0) -> None: ...
    def parse_range(self, fieldname, start, end, startexcl, endexcl, boost: float = 1.0) -> None: ...
    def separate_spelling(self): ...
    def spelling_fieldname(self, fieldname): ...
    def spellable_words(self, value): ...
    def subfields(self) -> Generator[Incomplete]: ...
    def supports(self, name): ...
    def clean(self) -> None: ...
    def on_add(self, schema, fieldname) -> None: ...
    def on_remove(self, schema, fieldname) -> None: ...

class FieldWrapper(FieldType):
    subfield: Incomplete
    name_prefix: Incomplete
    analyzer: Incomplete
    format: Incomplete
    column_type: Incomplete
    scorable: Incomplete
    stored: Incomplete
    unique: Incomplete
    indexed: Incomplete
    vector: Incomplete
    def __init__(self, subfield, prefix) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def to_bytes(self, value): ...
    def to_column_value(self, value): ...
    def from_bytes(self, bs): ...
    def from_column_value(self, value): ...
    def set_sortable(self, sortable) -> None: ...
    def sortable_terms(self, ixreader, fieldname): ...
    def default_column(self): ...
    def self_parsing(self): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0): ...
    def parse_range(self, fieldname, start, end, startexcl, endexcl, boost: float = 1.0) -> None: ...
    def subfields(self) -> Generator[Incomplete]: ...
    def supports(self, name): ...
    def clean(self) -> None: ...
    def on_add(self, schema, fieldname) -> None: ...
    def on_remove(self, schema, fieldname) -> None: ...

class ID(FieldType):
    analyzer: Incomplete
    format: Incomplete
    stored: Incomplete
    unique: Incomplete
    def __init__(self, stored: bool = False, unique: bool = False, field_boost: float = 1.0, sortable: bool = False, analyzer: Incomplete | None = None) -> None: ...

class IDLIST(FieldType):
    analyzer: Incomplete
    format: Incomplete
    stored: Incomplete
    unique: Incomplete
    def __init__(self, stored: bool = False, unique: bool = False, expression: Incomplete | None = None, field_boost: float = 1.0) -> None: ...

class NUMERIC(FieldType):
    sortable_typecode: Incomplete
    numtype: Incomplete
    bits: Incomplete
    stored: Incomplete
    unique: Incomplete
    decimal_places: Incomplete
    shift_step: Incomplete
    signed: Incomplete
    analyzer: Incomplete
    format: Incomplete
    default: Incomplete
    def __init__(self, numtype=..., bits: int = 32, stored: bool = False, unique: bool = False, field_boost: float = 1.0, decimal_places: int = 0, shift_step: int = 4, signed: bool = True, sortable: bool = False, default: Incomplete | None = None) -> None: ...
    def default_column(self): ...
    def is_valid(self, x): ...
    def index(self, num, **kwargs) -> Generator[Incomplete]: ...  # type: ignore[override]
    def prepare_number(self, x): ...
    def unprepare_number(self, x): ...
    def to_column_value(self, x): ...
    def from_column_value(self, x): ...
    def to_bytes(self, x, shift: int = 0): ...
    def sortable_to_bytes(self, x, shift: int = 0): ...
    def from_bytes(self, bs): ...
    def process_text(self, text, **kwargs): ...
    def self_parsing(self): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0): ...
    def parse_range(self, fieldname, start, end, startexcl, endexcl, boost: float = 1.0): ...
    def sortable_terms(self, ixreader, fieldname) -> Generator[Incomplete]: ...

class DATETIME(NUMERIC):
    def __init__(self, stored: bool = False, unique: bool = False, sortable: bool = False) -> None: ...
    def prepare_datetime(self, x): ...
    def to_column_value(self, x): ...
    def from_column_value(self, x): ...
    def to_bytes(self, x, shift: int = 0): ...
    def from_bytes(self, bs): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0): ...
    def parse_range(self, fieldname, start, end, startexcl, endexcl, boost: float = 1.0): ...

class BOOLEAN(FieldType):
    bytestrings: Incomplete
    trues: Incomplete
    falses: Incomplete
    stored: Incomplete
    format: Incomplete
    def __init__(self, stored: bool = False, field_boost: float = 1.0) -> None: ...
    def to_bytes(self, x): ...
    def index(self, bit, **kwargs): ...
    def self_parsing(self): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0): ...

class STORED(FieldType):
    indexed: bool
    stored: bool
    def __init__(self) -> None: ...

class COLUMN(FieldType):
    indexed: bool
    stored: bool
    column_type: Incomplete
    def __init__(self, columnobj: Incomplete | None = None) -> None: ...
    def to_bytes(self, v): ...
    def from_bytes(self, b): ...

class KEYWORD(FieldType):
    analyzer: Incomplete
    format: Incomplete
    scorable: Incomplete
    stored: Incomplete
    unique: Incomplete
    vector: Incomplete
    column_type: Incomplete
    def __init__(self, stored: bool = False, lowercase: bool = False, commas: bool = False, scorable: bool = False, unique: bool = False, field_boost: float = 1.0, sortable: bool = False, vector: Incomplete | None = None, analyzer: Incomplete | None = None) -> None: ...

class TEXT(FieldType):
    analyzer: Incomplete
    format: Incomplete
    column_type: Incomplete
    spelling: Incomplete
    spelling_prefix: Incomplete
    multitoken_query: Incomplete
    scorable: bool
    stored: Incomplete
    vector: Incomplete
    def __init__(self, analyzer: Incomplete | None = None, phrase: bool = True, chars: bool = False, stored: bool = False, field_boost: float = 1.0, multitoken_query: str = 'default', spelling: bool = False, sortable: bool = False, lang: Incomplete | None = None, vector: Incomplete | None = None, spelling_prefix: str = 'spell_') -> None: ...
    def subfields(self) -> Generator[Incomplete]: ...
    def separate_spelling(self): ...
    def spelling_fieldname(self, fieldname): ...

class SpellField(FieldType):
    format: Incomplete
    analyzer: Incomplete
    column_type: Incomplete
    scorabe: bool
    stored: bool
    unique: bool
    indexed: bool
    spelling: bool
    def __init__(self, analyzer) -> None: ...
    def index(self, value, boost: float = 1.0, **kwargs): ...
    def tokenzie(self, value, **kwargs): ...
    def process_text(self, qstring, mode: str = '', **kwargs): ...

class NGRAM(FieldType):
    scorable: bool
    analyzer: Incomplete
    format: Incomplete
    stored: Incomplete
    queryor: Incomplete
    def __init__(self, minsize: int = 2, maxsize: int = 4, stored: bool = False, field_boost: float = 1.0, queryor: bool = False, phrase: bool = False, sortable: bool = False) -> None: ...
    def self_parsing(self): ...
    def parse_query(self, fieldname, qstring, boost: float = 1.0): ...

class NGRAMWORDS(NGRAM):
    scorable: bool
    analyzer: Incomplete
    format: Incomplete
    stored: Incomplete
    queryor: Incomplete
    def __init__(self, minsize: int = 2, maxsize: int = 4, stored: bool = False, field_boost: float = 1.0, tokenizer: Incomplete | None = None, at: Incomplete | None = None, queryor: bool = False, sortable: bool = False) -> None: ...

class ReverseField(FieldWrapper):
    analyzer: Incomplete
    format: Incomplete
    scorable: bool
    stored: bool
    unique: bool
    vector: bool
    def __init__(self, subfield, prefix: str = 'rev_') -> None: ...
    def subfields(self) -> Generator[Incomplete]: ...

class MetaSchema(type):
    def __new__(cls, name, bases, attrs): ...
    def schema(self): ...

class Schema:
    def __init__(self, **fields) -> None: ...
    def copy(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __iter__(self): ...
    def __getitem__(self, name): ...
    def __len__(self) -> int: ...
    def __contains__(self, fieldname) -> bool: ...
    def to_bytes(self, fieldname, value): ...
    def items(self): ...
    def names(self, check_names: Incomplete | None = None): ...
    def clean(self) -> None: ...
    def add(self, name, fieldtype, glob: bool = False) -> None: ...
    def remove(self, fieldname) -> None: ...
    def indexable_fields(self, fieldname) -> Generator[Incomplete]: ...
    def has_scorable_fields(self): ...
    def stored_names(self): ...
    def scorable_names(self): ...

class SchemaClass(Incomplete):
    def __new__(cls, *args, **kwargs): ...

def ensure_schema(schema): ...
def merge_fielddict(d1, d2): ...
def merge_schema(s1, s2): ...
def merge_schemas(schemas): ...
