from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.analysis import Token as Token
from whoosh.compat import htmlescape as htmlescape

DEFAULT_CHARLIMIT: Incomplete

def mkfrag(text, tokens, startchar: Incomplete | None = None, endchar: Incomplete | None = None, charsbefore: int = 0, charsafter: int = 0): ...

class Fragment:
    text: Incomplete
    matches: Incomplete
    startchar: Incomplete
    endchar: Incomplete
    matched_terms: Incomplete
    def __init__(self, text, matches, startchar: int = 0, endchar: int = -1) -> None: ...
    def __len__(self) -> int: ...
    def overlaps(self, fragment): ...
    def overlapped_length(self, fragment): ...
    def __lt__(self, other): ...

def set_matched_filter(tokens, termset) -> Generator[Incomplete]: ...

class Fragmenter:
    def must_retokenize(self): ...
    def fragment_tokens(self, text, all_tokens) -> None: ...
    def fragment_matches(self, text, matched_tokens) -> None: ...

class WholeFragmenter(Fragmenter):
    charlimit: Incomplete
    def __init__(self, charlimit=...) -> None: ...
    def fragment_tokens(self, text, tokens): ...
NullFragmeter = WholeFragmenter

class SentenceFragmenter(Fragmenter):
    maxchars: Incomplete
    sentencechars: Incomplete
    charlimit: Incomplete
    def __init__(self, maxchars: int = 200, sentencechars: str = '.!?', charlimit=...) -> None: ...
    def fragment_tokens(self, text, tokens) -> Generator[Incomplete]: ...

class ContextFragmenter(Fragmenter):
    maxchars: Incomplete
    surround: Incomplete
    charlimit: Incomplete
    def __init__(self, maxchars: int = 200, surround: int = 20, charlimit=...) -> None: ...
    def fragment_tokens(self, text, tokens) -> Generator[Incomplete]: ...

class PinpointFragmenter(Fragmenter):
    maxchars: Incomplete
    surround: Incomplete
    autotrim: Incomplete
    charlimit: Incomplete
    def __init__(self, maxchars: int = 200, surround: int = 20, autotrim: bool = False, charlimit=...) -> None: ...
    def must_retokenize(self): ...
    def fragment_tokens(self, text, tokens): ...
    def fragment_matches(self, text, tokens) -> Generator[Incomplete]: ...

class FragmentScorer: ...

class BasicFragmentScorer(FragmentScorer):
    def __call__(self, f): ...

def SCORE(fragment): ...
def FIRST(fragment): ...
def LONGER(fragment): ...
def SHORTER(fragment): ...
def get_text(original, token, replace): ...

class Formatter:
    between: str
    def format_token(self, text, token, replace: bool = False) -> None: ...
    def format_fragment(self, fragment, replace: bool = False): ...
    def format(self, fragments, replace: bool = False): ...
    def __call__(self, text, fragments): ...

class NullFormatter(Formatter):
    def format_token(self, text, token, replace: bool = False): ...

class UppercaseFormatter(Formatter):
    between: Incomplete
    def __init__(self, between: str = '...') -> None: ...
    def format_token(self, text, token, replace: bool = False): ...

class HtmlFormatter(Formatter):
    template: str
    between: Incomplete
    tagname: Incomplete
    classname: Incomplete
    termclass: Incomplete
    attrquote: Incomplete
    maxclasses: Incomplete
    seen: Incomplete
    htmlclass: Incomplete
    def __init__(self, tagname: str = 'strong', between: str = '...', classname: str = 'match', termclass: str = 'term', maxclasses: int = 5, attrquote: str = '"') -> None: ...
    def format_token(self, text, token, replace: bool = False): ...
    def clean(self) -> None: ...

class GenshiFormatter(Formatter):
    qname: Incomplete
    between: Incomplete
    def __init__(self, qname: str = 'strong', between: str = '...') -> None: ...
    def format_token(self, text, token, replace: bool = False): ...
    def format_fragment(self, fragment, replace: bool = False): ...
    def format(self, fragments, replace: bool = False): ...

def top_fragments(fragments, count, scorer, order, minscore: int = 1): ...
def highlight(text, terms, analyzer, fragmenter, formatter, top: int = 3, scorer: Incomplete | None = None, minscore: int = 1, order=..., mode: str = 'query'): ...

class Highlighter:
    fragmenter: Incomplete
    scorer: Incomplete
    formatter: Incomplete
    order: Incomplete
    always_retokenize: Incomplete
    def __init__(self, fragmenter: Incomplete | None = None, scorer: Incomplete | None = None, formatter: Incomplete | None = None, always_retokenize: bool = False, order=...) -> None: ...
    def can_load_chars(self, results, fieldname): ...
    def highlight_hit(self, hitobj, fieldname, text: Incomplete | None = None, top: int = 3, minscore: int = 1): ...
