from _typeshed import Incomplete

class DocIdSet:
    def __eq__(self, other): ...
    def __neq__(self, other): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __contains__(self, i) -> bool: ...
    def __or__(self, other): ...
    def __and__(self, other): ...
    def __sub__(self, other): ...
    def copy(self) -> None: ...
    def add(self, n) -> None: ...
    def discard(self, n) -> None: ...
    def update(self, other) -> None: ...
    def intersection_update(self, other) -> None: ...
    def difference_update(self, other) -> None: ...
    def invert_update(self, size) -> None: ...
    def intersection(self, other): ...
    def union(self, other): ...
    def difference(self, other): ...
    def invert(self, size): ...
    def isdisjoint(self, other): ...
    def before(self, i) -> None: ...
    def after(self, i) -> None: ...
    def first(self) -> None: ...
    def last(self) -> None: ...

class BaseBitSet(DocIdSet):
    def byte_count(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def __contains__(self, i) -> bool: ...
    def first(self): ...
    def last(self): ...
    def before(self, i): ...
    def after(self, i): ...

class OnDiskBitSet(BaseBitSet):
    def __init__(self, dbfile, basepos, bytecount) -> None: ...
    def byte_count(self): ...

class BitSet(BaseBitSet):
    bits: Incomplete
    def __init__(self, source: Incomplete | None = None, size: int = 0) -> None: ...
    def byte_count(self): ...
    def to_disk(self, dbfile): ...
    @classmethod
    def from_bytes(cls, bs): ...
    @classmethod
    def from_disk(cls, dbfile, bytecount): ...
    def copy(self): ...
    def clear(self) -> None: ...
    def add(self, i) -> None: ...
    def discard(self, i) -> None: ...
    def update(self, iterable) -> None: ...
    def intersection_update(self, other): ...
    def difference_update(self, other): ...
    def invert_update(self, size) -> None: ...
    def union(self, other): ...
    def intersection(self, other): ...
    def difference(self, other): ...

class SortedIntSet(DocIdSet):
    data: Incomplete
    typecode: Incomplete
    def __init__(self, source: Incomplete | None = None, typecode: str = 'I') -> None: ...
    def copy(self): ...
    def size(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __nonzero__(self): ...
    __bool__ = __nonzero__
    def __contains__(self, i) -> bool: ...
    def add(self, i) -> None: ...
    def discard(self, i) -> None: ...
    def clear(self) -> None: ...
    def intersection_update(self, other) -> None: ...
    def difference_update(self, other) -> None: ...
    def intersection(self, other): ...
    def difference(self, other): ...
    def first(self): ...
    def last(self): ...
    def before(self, i): ...
    def after(self, i): ...

class ReverseIdSet(DocIdSet):
    idset: Incomplete
    limit: Incomplete
    def __init__(self, idset, limit) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, i) -> bool: ...
    def __iter__(self): ...
    def add(self, n) -> None: ...
    def discard(self, n) -> None: ...
    def first(self): ...
    def last(self): ...

ROARING_CUTOFF: Incomplete

class RoaringIdSet(DocIdSet):
    cutoff: Incomplete
    idsets: Incomplete
    def __init__(self, source: Incomplete | None = None) -> None: ...
    def __len__(self) -> int: ...
    def __contains__(self, n) -> bool: ...
    def __iter__(self): ...
    def add(self, n) -> None: ...
    def discard(self, n) -> None: ...

class MultiIdSet(DocIdSet):
    idsets: Incomplete
    offsets: Incomplete
    def __init__(self, idsets, offsets) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
