from _typeshed import Incomplete

class LockError(Exception): ...
class IndexError(Exception): ...

class IndexVersionError(IndexError):
    version: Incomplete
    release: Incomplete
    def __init__(self, msg, version, release: Incomplete | None = None) -> None: ...

class OutOfDateError(IndexError): ...
class EmptyIndexError(IndexError): ...

def create_in(dirname, schema, indexname: Incomplete | None = None): ...
def open_dir(dirname, indexname: Incomplete | None = None, readonly: bool = False, schema: Incomplete | None = None): ...
def exists_in(dirname, indexname: Incomplete | None = None): ...
def exists(storage, indexname: Incomplete | None = None): ...
def version_in(dirname, indexname: Incomplete | None = None): ...
def version(storage, indexname: Incomplete | None = None): ...

class Index:
    def close(self) -> None: ...
    def add_field(self, fieldname, fieldspec) -> None: ...
    def remove_field(self, fieldname) -> None: ...
    def latest_generation(self): ...
    def refresh(self): ...
    def up_to_date(self): ...
    def last_modified(self): ...
    def is_empty(self) -> None: ...
    def optimize(self) -> None: ...
    def doc_count_all(self): ...
    def doc_count(self): ...
    def searcher(self, **kwargs): ...
    def field_length(self, fieldname): ...
    def max_field_length(self, fieldname): ...
    def reader(self, reuse: Incomplete | None = None) -> None: ...
    def writer(self, **kwargs) -> None: ...
    def delete_by_term(self, fieldname, text, searcher: Incomplete | None = None) -> None: ...
    def delete_by_query(self, q, searcher: Incomplete | None = None) -> None: ...

def clean_files(storage, indexname, gen, segments) -> None: ...

class FileIndex(Index):
    storage: Incomplete
    indexname: Incomplete
    def __init__(self, storage, schema: Incomplete | None = None, indexname=...) -> None: ...
    @classmethod
    def create(cls, storage, schema, indexname=...): ...
    def close(self) -> None: ...
    def latest_generation(self): ...
    def last_modified(self): ...
    def is_empty(self): ...
    def optimize(self, **kwargs) -> None: ...
    def writer(self, procs: int = 1, **kwargs): ...
    def lock(self, name): ...
    @property
    def schema(self): ...
    @property
    def release(self): ...
    @property
    def version(self): ...
    def reader(self, reuse: Incomplete | None = None): ...

class TOC:
    schema: Incomplete
    segments: Incomplete
    generation: Incomplete
    version: Incomplete
    release: Incomplete
    def __init__(self, schema, segments, generation, version=..., release=...) -> None: ...
    @classmethod
    def create(cls, storage, schema, indexname=...) -> None: ...
    @classmethod
    def read(cls, storage, indexname, gen: Incomplete | None = None, schema: Incomplete | None = None): ...
    def write(self, storage, indexname) -> None: ...
