from _typeshed import Incomplete
from whoosh.compat import iteritems as iteritems

class WeightingModel:
    use_final: bool
    def idf(self, searcher, fieldname, text): ...
    def scorer(self, searcher, fieldname, text, qf: int = 1) -> None: ...
    def final(self, searcher, docnum, score): ...

class BaseScorer:
    def supports_block_quality(self): ...
    def score(self, matcher) -> None: ...
    def max_quality(self) -> None: ...
    def block_quality(self, matcher) -> None: ...

class WeightScorer(BaseScorer):
    def __init__(self, maxweight) -> None: ...
    def supports_block_quality(self): ...
    def score(self, matcher): ...
    def max_quality(self): ...
    def block_quality(self, matcher): ...
    @classmethod
    def for_(cls, searcher, fieldname, text): ...

class WeightLengthScorer(BaseScorer):
    dfl: Incomplete
    def setup(self, searcher, fieldname, text): ...
    def supports_block_quality(self): ...
    def score(self, matcher): ...
    def max_quality(self): ...
    def block_quality(self, matcher): ...

class DebugModel(WeightingModel):
    log: Incomplete
    def __init__(self) -> None: ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class DebugScorer(BaseScorer):
    searcher: Incomplete
    fieldname: Incomplete
    text: Incomplete
    log: Incomplete
    def __init__(self, searcher, fieldname, text, log) -> None: ...
    def supports_block_quality(self): ...
    def score(self, matcher): ...
    def max_quality(self): ...
    def block_quality(self, matcher): ...

def bm25(idf, tf, fl, avgfl, B, K1): ...

class BM25F(WeightingModel):
    B: Incomplete
    K1: Incomplete
    def __init__(self, B: float = 0.75, K1: float = 1.2, **kwargs) -> None: ...
    def supports_block_quality(self): ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class BM25FScorer(WeightLengthScorer):
    idf: Incomplete
    avgfl: Incomplete
    B: Incomplete
    K1: Incomplete
    qf: Incomplete
    def __init__(self, searcher, fieldname, text, B, K1, qf: int = 1) -> None: ...

def dfree(tf, cf, qf, dl, fl): ...

class DFree(WeightingModel):
    def supports_block_quality(self): ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class DFreeScorer(WeightLengthScorer):
    cf: Incomplete
    fl: Incomplete
    qf: Incomplete
    def __init__(self, searcher, fieldname, text, qf: int = 1) -> None: ...

rec_log2_of_e: Incomplete

def pl2(tf, cf, qf, dc, fl, avgfl, c): ...

class PL2(WeightingModel):
    c: Incomplete
    def __init__(self, c: float = 1.0) -> None: ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class PL2Scorer(WeightLengthScorer):
    cf: Incomplete
    dc: Incomplete
    avgfl: Incomplete
    c: Incomplete
    qf: Incomplete
    def __init__(self, searcher, fieldname, text, c, qf: int = 1) -> None: ...

class Frequency(WeightingModel):
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class TF_IDF(WeightingModel):
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class TF_IDFScorer(BaseScorer):
    idf: Incomplete
    def __init__(self, maxweight, idf) -> None: ...
    def supports_block_quality(self): ...
    def score(self, matcher): ...
    def max_quality(self): ...
    def block_quality(self, matcher): ...

class Weighting(WeightingModel):
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...
    def score(self, searcher, fieldname, text, docnum, weight) -> None: ...
    class CompatibilityScorer(BaseScorer):
        searcher: Incomplete
        fieldname: Incomplete
        text: Incomplete
        scoremethod: Incomplete
        def __init__(self, searcher, fieldname, text, scoremethod) -> None: ...
        def score(self, matcher): ...

class FunctionWeighting(WeightingModel):
    fn: Incomplete
    def __init__(self, fn) -> None: ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...
    class FunctionScorer(BaseScorer):
        fn: Incomplete
        searcher: Incomplete
        fieldname: Incomplete
        text: Incomplete
        qf: Incomplete
        def __init__(self, fn, searcher, fieldname, text, qf: int = 1) -> None: ...
        def score(self, matcher): ...

class MultiWeighting(WeightingModel):
    default: Incomplete
    weightings: Incomplete
    def __init__(self, default, **weightings) -> None: ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...

class ReverseWeighting(WeightingModel):
    weighting: Incomplete
    def __init__(self, weighting) -> None: ...
    def scorer(self, searcher, fieldname, text, qf: int = 1): ...
    class ReverseScorer(BaseScorer):
        subscorer: Incomplete
        def __init__(self, subscorer) -> None: ...
        def supports_block_quality(self): ...
        def score(self, matcher): ...
        def max_quality(self): ...
        def block_quality(self, matcher): ...
