from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.compat import iteritems as iteritems, izip as izip, string_type as string_type, xrange as xrange

class FacetType:
    maptype: Incomplete
    def categorizer(self, global_searcher) -> None: ...
    def map(self, default: Incomplete | None = None): ...
    def default_name(self): ...

class Categorizer:
    allow_overlap: bool
    needs_current: bool
    def set_searcher(self, segment_searcher, docoffset) -> None: ...
    def key_for(self, matcher, segment_docnum): ...
    def keys_for(self, matcher, segment_docnum): ...
    def key_to_name(self, key): ...

class FieldFacet(FacetType):
    fieldname: Incomplete
    reverse: Incomplete
    allow_overlap: Incomplete
    maptype: Incomplete
    def __init__(self, fieldname, reverse: bool = False, allow_overlap: bool = False, maptype: Incomplete | None = None) -> None: ...
    def default_name(self): ...
    def categorizer(self, global_searcher): ...

class ColumnCategorizer(Categorizer):
    def __init__(self, global_searcher, fieldname, reverse: bool = False) -> None: ...
    def set_searcher(self, segment_searcher, docoffset) -> None: ...
    def key_for(self, matcher, segment_docnum): ...
    def key_to_name(self, key): ...

class ReversedColumnCategorizer(ColumnCategorizer):
    def __init__(self, global_searcher, fieldname) -> None: ...
    def key_for(self, matcher, segment_docnum): ...
    def key_to_name(self, key): ...

class OverlappingCategorizer(Categorizer):
    allow_overlap: bool
    def __init__(self, global_searcher, fieldname) -> None: ...
    def set_searcher(self, segment_searcher, docoffset) -> None: ...
    def keys_for(self, matcher, docid): ...
    def key_for(self, matcher, docid): ...

class PostingCategorizer(Categorizer):
    reverse: Incomplete
    values: Incomplete
    array: Incomplete
    def __init__(self, global_searcher, fieldname, reverse) -> None: ...
    docoffset: Incomplete
    def set_searcher(self, segment_searcher, docoffset) -> None: ...
    def key_for(self, matcher, segment_docnum): ...
    def key_to_name(self, i): ...

class QueryFacet(FacetType):
    querydict: Incomplete
    other: Incomplete
    maptype: Incomplete
    allow_overlap: Incomplete
    def __init__(self, querydict, other: Incomplete | None = None, allow_overlap: bool = False, maptype: Incomplete | None = None) -> None: ...
    def categorizer(self, global_searcher): ...
    class QueryCategorizer(Categorizer):
        querydict: Incomplete
        other: Incomplete
        allow_overlap: Incomplete
        def __init__(self, querydict, other, allow_overlap: bool = False) -> None: ...
        docsets: Incomplete
        offset: Incomplete
        def set_searcher(self, segment_searcher, offset) -> None: ...
        def key_for(self, matcher, docid): ...
        def keys_for(self, matcher, docid) -> Generator[Incomplete]: ...

class RangeFacet(QueryFacet):
    fieldname: Incomplete
    start: Incomplete
    end: Incomplete
    gap: Incomplete
    hardend: Incomplete
    maptype: Incomplete
    def __init__(self, fieldname, start, end, gap, hardend: bool = False, maptype: Incomplete | None = None) -> None: ...
    def default_name(self): ...
    def categorizer(self, global_searcher): ...

class DateRangeFacet(RangeFacet): ...

class ScoreFacet(FacetType):
    def categorizer(self, global_searcher): ...
    class ScoreCategorizer(Categorizer):
        needs_current: bool
        use_final: Incomplete
        final: Incomplete
        def __init__(self, global_searcher) -> None: ...
        segment_searcher: Incomplete
        def set_searcher(self, segment_searcher, offset) -> None: ...
        def key_for(self, matcher, docid): ...

class FunctionFacet(FacetType):
    fn: Incomplete
    maptype: Incomplete
    def __init__(self, fn, maptype: Incomplete | None = None) -> None: ...
    def categorizer(self, global_searcher): ...
    class FunctionCategorizer(Categorizer):
        global_searcher: Incomplete
        fn: Incomplete
        def __init__(self, global_searcher, fn) -> None: ...
        offset: Incomplete
        def set_searcher(self, segment_searcher, docoffset) -> None: ...
        def key_for(self, matcher, docid): ...

class TranslateFacet(FacetType):
    fn: Incomplete
    facets: Incomplete
    maptype: Incomplete
    def __init__(self, fn, *facets) -> None: ...
    def categorizer(self, global_searcher): ...
    class TranslateCategorizer(Categorizer):
        fn: Incomplete
        catters: Incomplete
        def __init__(self, fn, catters) -> None: ...
        def set_searcher(self, segment_searcher, docoffset) -> None: ...
        def key_for(self, matcher, segment_docnum): ...

class StoredFieldFacet(FacetType):
    fieldname: Incomplete
    allow_overlap: Incomplete
    split_fn: Incomplete
    maptype: Incomplete
    def __init__(self, fieldname, allow_overlap: bool = False, split_fn: Incomplete | None = None, maptype: Incomplete | None = None) -> None: ...
    def default_name(self): ...
    def categorizer(self, global_searcher): ...
    class StoredFieldCategorizer(Categorizer):
        fieldname: Incomplete
        allow_overlap: Incomplete
        split_fn: Incomplete
        def __init__(self, fieldname, allow_overlap, split_fn) -> None: ...
        segment_searcher: Incomplete
        def set_searcher(self, segment_searcher, docoffset) -> None: ...
        def keys_for(self, matcher, docid): ...
        def key_for(self, matcher, docid): ...

class MultiFacet(FacetType):
    facets: Incomplete
    maptype: Incomplete
    def __init__(self, items: Incomplete | None = None, maptype: Incomplete | None = None) -> None: ...
    @classmethod
    def from_sortedby(cls, sortedby): ...
    def add_field(self, fieldname, reverse: bool = False): ...
    def add_query(self, querydict, other: Incomplete | None = None, allow_overlap: bool = False): ...
    def add_score(self): ...
    def add_facet(self, facet): ...
    def categorizer(self, global_searcher): ...
    class MultiCategorizer(Categorizer):
        catters: Incomplete
        def __init__(self, catters) -> None: ...
        @property
        def needs_current(self): ...
        def set_searcher(self, segment_searcher, docoffset) -> None: ...
        def key_for(self, matcher, docid): ...
        def key_to_name(self, key): ...

class Facets:
    facets: Incomplete
    def __init__(self, x: Incomplete | None = None) -> None: ...
    @classmethod
    def from_groupedby(cls, groupedby): ...
    def names(self): ...
    def items(self): ...
    def add_field(self, fieldname, **kwargs): ...
    def add_query(self, name, querydict, **kwargs): ...
    def add_facet(self, name, facet): ...
    def add_facets(self, facets, replace: bool = True): ...

class FacetMap:
    def add(self, groupname, docid, sortkey) -> None: ...
    def as_dict(self) -> None: ...

class OrderedList(FacetMap):
    dict: Incomplete
    def __init__(self) -> None: ...
    def add(self, groupname, docid, sortkey) -> None: ...
    def as_dict(self): ...

class UnorderedList(FacetMap):
    dict: Incomplete
    def __init__(self) -> None: ...
    def add(self, groupname, docid, sortkey) -> None: ...
    def as_dict(self): ...

class Count(FacetMap):
    dict: Incomplete
    def __init__(self) -> None: ...
    def add(self, groupname, docid, sortkey) -> None: ...
    def as_dict(self): ...

class Best(FacetMap):
    bestids: Incomplete
    bestkeys: Incomplete
    def __init__(self) -> None: ...
    def add(self, groupname, docid, sortkey) -> None: ...
    def as_dict(self): ...

def add_sortable(writer, fieldname, facet, column: Incomplete | None = None) -> None: ...
