import abc
import threading
import types
from _typeshed import Incomplete
from abc import abstractmethod
from collections.abc import Generator
from whoosh import columns as columns
bytes_type = bytes
from whoosh.externalsort import SortingPool as SortingPool
from whoosh.fields import UnknownFieldError as UnknownFieldError
from whoosh.index import LockError as LockError
from whoosh.system import emptybytes as emptybytes
from whoosh.util import fib as fib, random_name as random_name
from whoosh.util.filelock import try_for as try_for
from whoosh.util.text import utf8encode as utf8encode

class IndexingError(Exception): ...

def groupmanager(writer) -> Generator[None]: ...
def NO_MERGE(writer, segments): ...
def MERGE_SMALL(writer, segments): ...
def OPTIMIZE(writer, segments): ...
def CLEAR(writer, segments): ...

class PostingPool(SortingPool):
    namechars: str
    tempstore: Incomplete
    segment: Incomplete
    limit: Incomplete
    currentsize: int
    fieldnames: Incomplete
    def __init__(self, tempstore, segment, limitmb: int = 128, **kwargs) -> None: ...
    def add(self, item) -> None: ...
    def iter_postings(self): ...
    def save(self) -> None: ...

class IndexWriter(metaclass=abc.ABCMeta):
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def group(self): ...
    def start_group(self) -> None: ...
    def end_group(self) -> None: ...
    def add_field(self, fieldname, fieldtype, **kwargs) -> None: ...
    def remove_field(self, fieldname, **kwargs) -> None: ...
    @abstractmethod
    def reader(self, **kwargs): ...
    def searcher(self, **kwargs): ...
    def delete_by_term(self, fieldname, text, searcher: Incomplete | None = None): ...
    def delete_by_query(self, q, searcher: Incomplete | None = None): ...
    @abstractmethod
    def delete_document(self, docnum, delete: bool = True): ...
    @abstractmethod
    def add_document(self, **fields): ...
    @abstractmethod
    def add_reader(self, reader): ...
    def update_document(self, **fields) -> None: ...
    def commit(self) -> None: ...
    def cancel(self) -> None: ...

class SegmentWriter(IndexWriter):
    writelock: Incomplete
    codec: Incomplete
    storage: Incomplete
    indexname: Incomplete
    generation: Incomplete
    schema: Incomplete
    segments: Incomplete
    docnum: Incomplete
    newsegment: Incomplete
    compound: Incomplete
    is_closed: bool
    pool: Incomplete
    perdocwriter: Incomplete
    fieldwriter: Incomplete
    merge: bool
    optimize: bool
    mergetype: Incomplete
    def __init__(self, ix, poolclass: Incomplete | None = None, timeout: float = 0.0, delay: float = 0.1, _lk: bool = True, limitmb: int = 128, docbase: int = 0, codec: Incomplete | None = None, compound: bool = True, **kwargs) -> None: ...
    def temp_storage(self): ...
    def add_field(self, fieldname, fieldspec, **kwargs) -> None: ...  # type: ignore[override]
    def remove_field(self, fieldname) -> None: ...  # type: ignore[override]
    def has_deletions(self): ...
    def delete_document(self, docnum, delete: bool = True) -> None: ...
    def deleted_count(self): ...
    def is_deleted(self, docnum): ...
    def reader(self, reuse: Incomplete | None = None): ...  # type: ignore[override]
    def iter_postings(self): ...
    def add_postings_to_pool(self, reader, startdoc, docmap) -> None: ...
    def write_postings(self, lengths, items, startdoc, docmap) -> None: ...
    def write_per_doc(self, fieldnames, reader): ...
    def add_reader(self, reader) -> None: ...
    def add_document(self, **fields) -> None: ...
    def doc_count(self): ...
    def get_segment(self): ...
    def per_document_reader(self): ...
    def commit(self, mergetype: Incomplete | None = None, optimize: Incomplete | None = None, merge: Incomplete | None = None) -> None: ...
    def cancel(self) -> None: ...

class AsyncWriter(threading.Thread, IndexWriter, metaclass=abc.ABCMeta):
    running: bool
    index: Incomplete
    writerargs: Incomplete
    delay: Incomplete
    events: Incomplete
    writer: Incomplete
    def __init__(self, index, delay: float = 0.25, writerargs: Incomplete | None = None) -> None: ...
    def reader(self): ...
    def searcher(self, **kwargs): ...
    def run(self) -> None: ...
    def delete_document(self, *args, **kwargs) -> None: ...
    def add_document(self, *args, **kwargs) -> None: ...
    def update_document(self, *args, **kwargs) -> None: ...
    def add_field(self, *args, **kwargs) -> None: ...
    def remove_field(self, *args, **kwargs) -> None: ...
    def delete_by_term(self, *args, **kwargs) -> None: ...
    def commit(self, *args, **kwargs) -> None: ...
    def cancel(self, *args, **kwargs) -> None: ...

def add_spelling(ix, fieldnames, commit: bool = True) -> None: ...

class BufferedWriter(IndexWriter):
    index: Incomplete
    period: Incomplete
    limit: Incomplete
    writerargs: Incomplete
    commitargs: Incomplete
    lock: Incomplete
    writer: Incomplete
    bufferedcount: int
    timer: Incomplete
    def __init__(self, index, period: int = 60, limit: int = 10, writerargs: Incomplete | None = None, commitargs: Incomplete | None = None) -> None: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    @property
    def schema(self): ...
    def reader(self, **kwargs): ...
    def searcher(self, **kwargs): ...
    def close(self) -> None: ...
    def commit(self, restart: bool = True) -> None: ...
    def add_reader(self, reader) -> None: ...
    def add_document(self, **fields) -> None: ...
    def update_document(self, **fields) -> None: ...
    def delete_document(self, docnum, delete: bool = True) -> None: ...
    def is_deleted(self, docnum): ...
BatchWriter = BufferedWriter
