from _typeshed import Incomplete
from collections import defaultdict as defaultdict
from collections.abc import Generator
from whoosh.compat import iteritems as iteritems, next as next, text_type as text_type, unichr as unichr, xrange as xrange

unull: Incomplete

class Marker:
    name: Incomplete
    def __init__(self, name) -> None: ...

EPSILON: Incomplete
ANY: Incomplete

class FSA:
    initial: Incomplete
    transitions: Incomplete
    final_states: Incomplete
    def __init__(self, initial) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def all_states(self): ...
    def all_labels(self): ...
    def get_labels(self, src): ...
    def generate_all(self, state: Incomplete | None = None, sofar: str = '') -> Generator[Incomplete]: ...
    def start(self): ...
    def next_state(self, state, label) -> None: ...
    def is_final(self, state) -> None: ...
    def add_transition(self, src, label, dest) -> None: ...
    def add_final_state(self, state) -> None: ...
    def to_dfa(self) -> None: ...
    def accept(self, string, debug: bool = False): ...
    def append(self, fsa) -> None: ...

class NFA(FSA):
    transitions: Incomplete
    final_states: Incomplete
    initial: Incomplete
    def __init__(self, initial) -> None: ...
    def dump(self, stream=...) -> None: ...
    def start(self): ...
    def add_transition(self, src, label, dest) -> None: ...
    def add_final_state(self, state) -> None: ...
    def triples(self) -> Generator[Incomplete]: ...
    def is_final(self, states): ...
    def next_state(self, states, label): ...
    def get_labels(self, states): ...
    def embed(self, other) -> None: ...
    def insert(self, src, other, dest) -> None: ...
    def to_dfa(self): ...

class DFA(FSA):
    initial: Incomplete
    transitions: Incomplete
    defaults: Incomplete
    final_states: Incomplete
    outlabels: Incomplete
    def __init__(self, initial) -> None: ...
    def dump(self, stream=...) -> None: ...
    def start(self): ...
    def add_transition(self, src, label, dest) -> None: ...
    def set_default_transition(self, src, dest) -> None: ...
    def add_final_state(self, state) -> None: ...
    def is_final(self, state): ...
    def next_state(self, src, label): ...
    def next_valid_string(self, string, asbytes: bool = False): ...
    def find_next_edge(self, s, label, asbytes): ...
    def reachable_from(self, src, inclusive: bool = True): ...
    def minimize(self) -> None: ...
    def to_dfa(self): ...

def renumber_dfa(dfa, base: int = 0): ...
def u_to_utf8(dfa, base: int = 0) -> None: ...
def find_all_matches(dfa, lookup_func, first=...) -> Generator[Incomplete]: ...
def reverse_nfa(n): ...
def product(dfa1, op, dfa2): ...
def intersection(dfa1, dfa2): ...
def union(dfa1, dfa2): ...
def epsilon_nfa(): ...
def dot_nfa(): ...
def basic_nfa(label): ...
def charset_nfa(labels): ...
def string_nfa(string): ...
def choice_nfa(n1, n2): ...
def concat_nfa(n1, n2): ...
def star_nfa(n): ...
def plus_nfa(n): ...
def optional_nfa(n): ...

class DMNode:
    n: Incomplete
    arcs: Incomplete
    final: bool
    def __init__(self, n) -> None: ...
    def __hash__(self): ...
    def tuple(self): ...

def strings_dfa(strings): ...
def add_suffix(dfa, nodes, last, downto, seen) -> None: ...
