from _typeshed import Incomplete
from collections.abc import Generator
from whoosh.automata.fst import Arc as Arc

class Instruction: ...

class Char(Instruction):
    c: Incomplete
    def __init__(self, c) -> None: ...

class Lit(Instruction):
    c: Incomplete
    def __init__(self, c) -> None: ...

class Any(Instruction): ...
class Match(Instruction): ...

class Jmp(Instruction):
    x: Incomplete
    def __init__(self, x) -> None: ...

class Split(Instruction):
    x: Incomplete
    y: Incomplete
    def __init__(self, x, y) -> None: ...

class Label(Instruction):
    def __hash__(self): ...

def concat(e1, e2): ...
def alt(e1, e2): ...
def zero_or_one(e): ...
def zero_or_more(e): ...
def one_or_more(e): ...
def fixup(program): ...

class ThreadList:
    program: Incomplete
    max: Incomplete
    threads: Incomplete
    def __init__(self, program, max: int = 1000) -> None: ...
    def __nonzero__(self): ...
    def current(self): ...
    def add(self, thread) -> None: ...

class Thread:
    pc: Incomplete
    address: Incomplete
    sofar: Incomplete
    accept: Incomplete
    def __init__(self, pc, address, sofar: str = '', accept: bool = False) -> None: ...
    def at(self, pc): ...
    def copy_at(self, pc): ...

def advance(thread, arc, c) -> None: ...
def run(graph, program, address) -> Generator[Incomplete]: ...

LO: int
HI: int

def regex_limit(graph, mode, program, address): ...
