from _typeshed import Incomplete
from whoosh.automata.fsa import ANY as ANY, EPSILON as EPSILON, NFA as NFA

CHOICE: Incomplete
ops: Incomplete

def parse(pattern) -> None: ...

class RegexBuilder:
    statenum: int
    def __init__(self) -> None: ...
    def new_state(self): ...
    def epsilon(self): ...
    def char(self, label): ...
    def charset(self, chars): ...
    def dot(self): ...
    def choice(self, n1, n2): ...
    def concat(self, n1, n2): ...
    def star(self, n): ...
    def plus(self, n): ...
    def question(self, n): ...
